---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: redis
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:5.*

spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 6.4.3
  values:
    image:
      repository: bitnami/redis
      tag: "5.0"
      pullPolicy: IfNotPresent

    usePassword: false
    master:
      persistence:
        enabled: false
    cluster:
      enabled: false

    metrics:
      enabled: false
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9121"
