apiVersion: extensions/v1beta1
kind: DaemonSet

metadata:
  name: do-node-agent
  namespace: kube-system
  labels:
    app: do-node-agent

spec:
  selector:
    matchLabels:
      app: do-node-agent
  template:
    metadata:
      labels:
        app: do-node-agent
    spec:
      containers:
      - name: do-node-agent
        image: docker.io/digitalocean/do-agent:2.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/do-agent"]
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
        resources:
          limits:
            cpu: 102m
            memory: 100Mi
          requests:
            cpu: 102m
            memory: 80Mi
        volumeMounts:
          - mountPath: /host/proc
            name: proc
            readOnly: true
          - mountPath: /host/sys
            name: sys
            readOnly: true
          - mountPath: /host/root
            mountPropagation: HostToContainer
            name: root
            readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: ""
        - name: sys
          hostPath:
            path: /sys
            type: ""
        - name: root
          hostPath:
            path: /
            type: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: do-agent
      terminationGracePeriodSeconds: 30
      nodeSelector:
        beta.kubernetes.io/os: linux
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
