---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.13
  labels:
    app: cert-manager

spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.3
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.0.3

    installCRDs: true

    global:
      leaderElection:
        namespace: cert-manager

    prometheus:
      enabled: false
