---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.11
  labels:
    app: cert-manager

spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.11.0
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v0.11.0
