---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "false"
  labels:
    app.kubernetes.io/name: cert-manager

spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.7.0
