---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cloudflare
  namespace: cert-manager

spec:
  encryptedData:
    apiKey: AgB//0PBcmt66rRIb38Vzhu6rknKdSuMvWy7tUBvPJj38s/KTQ8nacRGKuHq8bH8/F8k58mvJmy0NUoQSfdbP4kanzM/Bxz7CFRxRfkfzeT7AhkaWxpYWE7P6QmRy5V4XxPWKDZTf0rTjjc0Uq23qldyOecp1QpjHifO2YRdt/Zy0GNO1i3ONQMDyn7jg+aZ7SAPbTkYMZ4PA5ItIymBWOQwICdSd2fhW/Xi+UbjEd1228OSIL2dM+gqeZ0uZkCtRTIDc4DobGWswYlDUGr9MmhduSSiOWYTQM5B8tNBgW9LS418fWRPNCeWqXNtsTw40Pa/zDQNEvO00TC16SLuh0jP4GgqT/5hQEdNCRP1XPQumx1X01BkotnYywRT4Rm/0Jc94VClIG7XDgLBS7WBupDlIanwI+HPQn7RfsqqERXl5dAgh18W8Hu/KbNJ8WgoQPvSRKfdb3zM4cIUeKSb4cqop+NNmPJB9t9bx8J+KOGllov8G9qQCNDQd3TqGd9mFeGzy27LF5SPYZnhphUEK1m2l6yZmTtjEKnRmaokFaaPnYtelBNYNT8nl79WPJ15J4YnbqagGzPBL/3UPHL35URX370mjgu3tRUFjQ0oFo/nECJEsGPM+Z+vl+MJ4+CZg+CqwGnrZentm1z70tyFexMCsZEoUiLonxixuBLVOPZlYqxcNaHk67oyGzl5HLd87HlJDtTmTbxNMYv6FrmwiQQCd6al7UzFK1U0ekYYumr9YxGdop/n
