---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: http-debug
  namespace: default
  annotations:
    flux.weave.works/ignore: "true"

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: http-debug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-debug
    spec:
      containers:
        - name: http-debug
          image: mendhak/http-https-echo
          imagePullPolicy: Always
          ports:
            - name: http1
              containerPort: 80
              hostPort: 80

---

apiVersion: v1
kind: Service

metadata:
  name: http-debug
  namespace: default
  labels:
    app.kubernetes.io/name: http-debug

spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: http-debug
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30001
