---

apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: default

spec:
  description: Apps for stevenxie.me.
  sourceRepos: ["https://github.com/stevenxie/columbia"]
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
