---

apiVersion: v1
kind: Service

metadata:
  name: ingress-nodeports
  namespace: istio-system

spec:
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
    - name: frps
      port: 30070
      targetPort: 30070
      nodePort: 30070
    - name: ssh
      port: 30022
      targetPort: 30022
      nodePort: 30022
    # Multicluster ingress endpoint (disabled).
    # - name: tls
    #   port: 30443
    #   targetPort: 15443
    #   nodePort: 30443
