---

apiVersion: v1
kind: Service

metadata:
  name: rgv-frontend
  namespace: stevenxie
  labels:
    app: rgv-frontend

spec:
  selector:
    app: rgv-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
