---

apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image

metadata:
  name: gcs-fetcher
  namespace: knative-build
  annotations:
    flux.weave.works/ignore: "true"

spec:
  image: gcr.io/cloud-builders/gcs-fetcher
