---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: weave-scope-cluster-agent
  namespace: weave-scope
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/scope-cluster-agent: semver:~1
  labels:
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: cluster-agent

spec:
  selector:
    matchLabels:
      app: weave-scope
      weave-cloud-component: scope
      weave-scope-component: cluster-agent
  template:
    metadata:
      labels:
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: cluster-agent
    spec:
      serviceAccountName: weave-scope
      containers:
      - name: scope-cluster-agent
        image: weaveworks/scope:1.12.0
        imagePullPolicy: IfNotPresent
        command: ["/home/weave/scope"]
        args:
        - --mode=probe
        - --probe-only
        - --probe.kubernetes.role=cluster
        - --probe.no-controls=true
        - --probe.spy.interval=5s
        - --probe.publish.interval=5s
        - --weave=false
        - weave-scope-app:80
        resources:
          requests:
            cpu: 2m
            memory: 40Mi
          limits:
            cpu: 20m
            memory: 100Mi
