---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: weave-scope-app
  namespace: weave-scope
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.app: semver:~1
  labels:
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: app

spec:
  selector:
    matchLabels:
      app: weave-scope
      weave-cloud-component: scope
      weave-scope-component: app
  template:
    metadata:
      labels:
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
    spec:
      containers:
      - name: app
        image: weaveworks/scope:1.12.0
        imagePullPolicy: IfNotPresent
        command: ["/home/weave/scope"]
        args:
        - --mode=app
        - --app-only
        - --weave=false
        ports:
        - containerPort: 4040
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 125Mi
          limits:
            cpu: 100m
            memory: 400Mi
