---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: letsencrypt-staging

spec:
  acme:
    email: dev@stevenxie.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: steven.xie@outlook.com
            apiKeySecretRef:
              name: cloudflare
              key: apiKey
