---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: knative-serving-istio
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/controller: "true"
    serving.knative.dev/release: devel

rules:
  - apiGroups: ["networking.istio.io"]
    resources:
      - virtualservices
      - gateways
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
