---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: knative-serving-admin
  labels:
    serving.knative.dev/release: devel

rules: []

aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        serving.knative.dev/controller: "true"
