---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: drone
  namespace: drone
  labels:
    app: drone

spec:
  metadata:
    name: drone
    namespace: drone
    labels:
      app: drone

  encryptedData:
    DRONE_GITHUB_CLIENT_SECRET: AgAz2WGKZQ9If7gB3k1hiOhcoT9DcV2fM2+SrKfrZs8k3UbvNe6v8NhpruS6lwmG5BpPy36dSfrJVe3TsCDQZ0i8wD0VtkqxRJoYhMXN/6CWL9N9k46mw/6OJ3l9N34NbiqIs6KSXv+2RqTGU0ZBXE4fLIThVT97Vb7pIikitc1dZ4UWZja+t0UnWKn0f0z5m9avQv7GfS3VXGdo0rUmnIgqIgjkuzd9rya5W4KIaZTgb6/F77KYyI0p1ChR+mL8QgT+eYjlsbwa9IP4gS8zhbJWaEkj6Ak715FqXi1qfWb9i6gGrnWtnCAnnpw+8/UpdVGNeRCFEQo4CzapkkIve6yUSvq/sF9O+iUBR1KaQqey4z8S+9nO7+u53tSOFCWaEiFSYHrT4ff5DOMKPWNBeF3o3HmzUbos7jGQT8RdS2oUzJMTfjAgklKrOrjqHMP9UgGmUYzjHrPlERvSWDQ84lVpQPYVFcPJRtdLEKx1rAJgQ90cGa86ABx6R8Bo7qiO7NF14te7jg9+oNmUvrWyUWTBOhZiwUA4+KMN7C/AMpAHmblKNRLyfnrc/spRmEiztvFpLB8u9dTVhwr3UUl6IZzmirk5DPO++JvfhWJPV/3n0DXRcK+GukZ/avMQZa1bRnnxpte32+vtmYw4QZeb4MEbStRIlcVmL29ajQ3S4nONx8Fo6EnUKc51wIVPQwNWL3xAoUTH1BkWApToYcDyAnMX9UvLSNZo8m3tstqjnayF4SvUj0JB0ymV
    DRONE_RPC_SECRET: AgC+vo4FgSouTkKchcFCvgwP6GxKkmvKCg4RbSn37OhIP9UbzIs1A47AgGXv3v3ZLkyRtK/8xx4L+bMNZNXlVaNnwHACUZ4eE0Gvix7VHaIoW2jezoPdRMzoD8nXkfSFqkkZnFxMfoLpDn/S/I9kuk4xnI/EN1PwYqAJHplcx1bDcvvJCppSAwi1TCNPopvKhB4vKWve1ARJFx2S7tQqY2Ez81508/IrEZt4AvmOKe08YB9I+mx/9O3dI3C/xEbhR1iQy2ixw2JFpvql+90FxzP0cfyppbYxJSVqg9bG3Jwxrz+R1lzdJ5HDi79IQpSK4VioWMvaqopVqEX25nIkwJTFsUUT/VZub5KNWMkiD0ct1zIMJQYoQMGPnk83gkLgfyxF3i56VfzgOo71MFMd9pYRGvG52/Lnk5nxLzAmaz9Q6TvUGr1tUdAL+u5ffNfFk/joKGpuziM/Z90HV9gluzFZYQKtLM5J7O1BEoEuOZGYOPv167dyx2EbBQhsn6oj0BTDl4LwlCI8ImsXGFkyVndydzXduNJ8aPXPMHi6MYd08JSbaUL4uGunDKXB8uj28mYWzV6wzkTWqSgZCaLRhhaiMofFUUXX5n47Q2iPdwnbDeXf8e/1CaqP3qbOAV4Y114wG0aRxJTSrH9HnqO/KOXyOkSJjNDxRvULuu0d94YkdYXZG4HLAcTgNhZk410kIaYIlas7o9HT2QTFdltwJRP/6r4zkApqvko5JVCF+2IusAvWIjLSXhjD62fgmjrcpza1i9G3dLjP46uM8J4EjZ0R
