---

apiVersion: serving.knative.dev/v1alpha1
kind: Service

metadata:
  name: debug
  namespace: functions
  labels:
    app.kubernetes.io/name: debug

spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            app.kubernetes.io/name: debug
          annotations:
            flux.weave.works/automated: "false"
        spec:
          container:
            image: mendhak/http-https-echo:latest
            ports:
              - name: http1
                containerPort: 80
