---

apiVersion: v1
kind: Service

metadata:
  name: build-controller
  namespace: knative-build
  labels:
    app: build-controller

spec:
  selector:
    app: build-controller
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
