---

apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image

metadata:
  name: creds-init
  namespace: knative-build

spec:
  image: gcr.io/knative-releases/github.com/knative/build/cmd/creds-init:v0.5.0
