---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: api
  namespace: uwcnc

spec:
  entryPoints: ["websecure"]
  routes:
    - match: Host(`api.uwcoffeencode.com`) && (Path(`/`, `/graphql`) || PathPrefix(`/static`))
      kind: Rule
      services:
        - name: barista
          port: 80
  tls:
    secretName: tls-uwcoffeencode-com
