---

apiVersion: v1
kind: Service

metadata:
  name: barista
  namespace: uwcnc
  labels:
    app: barista

spec:
  selector:
    app: barista
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: barista
  namespace: uwcnc
  labels:
    app: barista

spec:
  gateways: ["uwcoffeencode-com.istio-system"]
  hosts: ["api.uwcoffeencode.com"]
  http:
    - route:
        - destination:
            host: barista
            port:
              number: 80
          headers:
            response:
              set:
                X-Service: barista
