---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: barista
  namespace: uwcnc
  labels:
    app: barista
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: regexp:^0(\.[0-9]+){2} # 0.x.x...
    filter.fluxcd.io/migrate: regexp:^0(\.[0-9]+){2} # 0.x.x...

spec:
  selector:
    matchLabels:
      app: barista
  template:
    metadata:
      labels:
        app: barista
    spec:
      initContainers:
      - name: migrate
        image: uwcoffeencode/barista:0.1.0-6-g5454e3c
        command: ["python", "manage.py"]
        args: ["migrate"]
        envFrom: &env
        - configMapRef:
            name: barista
        - secretRef:
            name: barista
      containers:
      - name: app
        image: uwcoffeencode/barista:0.1.0-6-g5454e3c
        envFrom: *env
        ports:
        - name: http
          containerPort: 80
        readinessProbe: &probe
          initialDelaySeconds: 20
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
            - name: Host
              value: localhost
        livenessProbe: *probe
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 500Mi
