apiVersion: v1
kind: Service

metadata:
  name: fission-router
  namespace: fission
  annotations:
    flux.weave.works/ignore: "true"
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: fission
      service: router.fission
      host: fission.stevenxie.me
      prefix: /
      add_response_headers:
        X-Service: fission-router

spec:
  selector:
    svc: router
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
