---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-1.0

resources:
  - argocd-server.vs.yaml
  - argocd-secret.ss.yaml
  - projects/columbia-system.appproj.yaml
  - projects/default.appproj.yaml

patchesStrategicMerge:
  - overlays/argocd-dex-server.deploy.yaml
  - overlays/argocd-server.deploy.yaml
  - overlays/argocd-server.svc.yaml
  - overlays/argocd-cm.cm.yaml
