---

apiVersion: v1
kind: Service

metadata:
  name: barista
  namespace: uwcnc
  labels:
    app: barista

spec:
  selector:
    app: barista
  ports:
    - name: http
      port: 80
      targetPort: http
