---

apiVersion: v1
kind: Service

metadata:
  name: kidsability-checkout-assistant
  namespace: stevenxie
  labels:
    app: kidsability-checkout-assistant

spec:
  selector:
    app: kidsability-checkout-assistant
  ports:
    - name: http
      port: 80
      targetPort: http
