---

apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: stevenxie-com
  namespace: stevenxie

spec:
  commonName: stevenxie.com
  secretName: tls-stevenxie-com
  dnsNames:
    - stevenxie.com
    - "*.stevenxie.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
