---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: fs-debug
  namespace: default
  annotations:
    flux.weave.works/ignore: "true"
  labels:
    app.kubernetes.io/name: fs-debug

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fs-debug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fs-debug
    spec:
      containers:
        - name: fs-debug
          image: alpine
          imagePullPolicy: Always
          command: ["tail"]
          args:
            - -f
            - /dev/null
          volumeMounts:
            - name: host
              mountPath: /host
          securityContext:
            privileged: true
      volumes:
        - name: host
          hostPath:
            type: Directory
            path: /
