---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
  name: admin
  namespace: wanderfall

rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - batch
    resources: ['*']
    verbs: ['*']

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: admin
  namespace: wanderfall

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: wanderfall
