---

apiVersion: v1
kind: Service

metadata:
  name: ghost
  namespace: wanderfall
  labels:
    app.kubernetes.io/name: ghost

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ghost
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: ghost
  namespace: wanderfall

spec:
  gateways: ["wanderfall.istio-system"]
  hosts:
    - wanderfallgames.com
    - www.wanderfallgames.com
  http:
    - match:
        - authority:
            exact: www.wanderfallgames.com
      redirect:
        authority: wanderfallgames.com
    - route:
        - destination:
            host: ghost
          headers:
            response:
              set:
                X-Service: ghost
