---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: ghost
  namespace: wanderfall
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.ghost: regexp:^2(\.[0-9]+){2}-alpine$
  labels:
    app.kubernetes.io/name: ghost

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:2.19.4-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: url
              value: https://wanderfallgames.com
          volumeMounts:
            - name: content
              mountPath: /var/lib/ghost/content
          ports:
            - name: http
              containerPort: 2368
          livenessProbe: &probe
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: wanderfallgames.com
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 5
          readinessProbe: *probe
          resources:
            requests:
              cpu: 5m
              memory: 10M
            limits:
              cpu: 250m
              memory: 350Mi
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: ghost

---

apiVersion: v1
kind: Service

metadata:
  name: ghost
  namespace: wanderfall
  labels:
    app.kubernetes.io/name: ghost

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ghost
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: ghost
  namespace: wanderfall

spec:
  gateways: ["wanderfall.istio-system"]
  hosts:
    - wanderfallgames.com
    - www.wanderfallgames.com
  http:
    - route:
        - destination:
            host: ghost
          headers:
            response:
              set:
                X-Service: ghost
    - match:
        - authority:
            exact: www.wanderfallgames.com
      redirect:
        authority: wanderfallgames.com
