---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: ghost
  namespace: wanderfall
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.ghost: regexp:^2(\.[0-9]+){2}-alpine$
  labels:
    app: ghost

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ghost
  serviceName: ghost
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghost
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:2.37.0-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: url
          value: https://wanderfallgames.com
        volumeMounts:
        - name: content
          mountPath: /var/lib/ghost/content
        ports:
        - name: http
          containerPort: 2368
        livenessProbe: &probe
          httpGet:
            path: /
            port: 2368
            httpHeaders:
            - name: Host
              value: wanderfallgames.com
            - name: X-Forwarded-Proto
              value: https
          initialDelaySeconds: 10
        readinessProbe: *probe
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            cpu: 250m
            memory: 350Mi
  volumeClaimTemplates:
  - metadata:
      name: content
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
