---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry

metadata:
  name: monastery-weave-scope-app
  namespace: proxy

spec:
  hosts: ["weave-scope-app.weave-scope.global"]
  location: MESH_INTERNAL
  resolution: DNS
  addresses: ["127.255.0.1"]
  ports:
    - name: http1
      number: 80
      protocol: http
  endpoints:
    - address: frps.proxy.svc.cluster.local
      ports:
        http1: 15443

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: monastery-weave-scope-app
  namespace: proxy

spec:
  gateways: ["primary.istio-system"]
  hosts: ["monastery.stevenxie.me"]
  http:
    - rewrite:
        authority: weave-scope-app.weave-scope.global
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
            port:
              number: 80
