---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: helmreleases.flux.weave.works
  labels:
    app.kubernetes.io/name: flux

spec:
  group: flux.weave.works
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    shortNames: ['hr']
  scope: Namespaced
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ['chart']
          properties:
            releaseName:
              type: string
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            timeout:
              type: integer
              format: int64
            resetValues:
              type: boolean
            forceUpgrade:
              type: boolean
            valueFileSecrets:
              type: array
              items:
                type: object
                required: ['name']
                properties:
                  name:
                    type: string
            valuesFrom:
              type: array
              items:
                type: object
                properties:
                  configMapKeyRef:
                    type: object
                    required: ['name']
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                      optional:
                        type: boolean
                  secretKeyRef:
                    type: object
                    required: ['name']
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                      optional:
                        type: boolean
                  externalSourceRef:
                    type: object
                    required: ['url']
                    properties:
                      url:
                        type: string
                      optional:
                        type: boolean
                oneOf:
                  - required: ['configMapKeyRef']
                  - required: ['secretKeyRef']
                  - required: ['externalSourceRef']
            values:
              type: object
            chart:
              oneOf:
                - required: ['git', 'path']
                  properties:
                    git:
                      type: string
                      format: git # not defined by OAS
                    path:
                      type: string
                    ref:
                      type: string
                    skipDepUpdate:
                      type: boolean
                - required: ['repository', 'name', 'version']
                  properties:
                    repository:
                      type: string
                      format: url # not defined by OAS
                    name:
                      type: string
                    version:
                      type: string
                      format: semver # not defined by OAS
                    chartPullSecret:
                      properties:
                        name:
                          type: string
