---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: serverlessservices.networking.internal.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  group: networking.internal.knative.dev
  names:
    categories:
      - all
      - knative-internal
      - networking
    kind: ServerlessService
    plural: serverlessservices
    shortNames: ["sks"]
    singular: serverlessservice
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
