---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: admin
  namespace: rcfta

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
  name: admin
  namespace: rcfta

rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - batch
    resources: ['*']
    verbs: ['*']

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: admin
  namespace: rcfta

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin

subjects:
  - kind: ServiceAccount
    name: admin
    namespace: rcfta

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: rcfta-admin-view

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

subjects:
  - kind: ServiceAccount
    name: admin
    namespace: rcfta

---

  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding

  metadata:
    name: rcfta-admin-node-view

  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: node-view

  subjects:
    - kind: ServiceAccount
      name: admin
      namespace: rcfta
