---

apiVersion: v1
kind: Service

metadata:
  name: dft
  namespace: rcfta
  labels:
    app: dft

spec:
  selector:
    app: dft
  ports:
    - name: http
      port: 8080
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: dft
  namespace: rcfta
  labels:
    app: dft

spec:
  gateways: ["primary.istio-system"]
  hosts: ["dft.stevenxie.me"]
  http:
    - route:
        - destination:
            host: dft
            port:
              number: 8080
          headers:
            response:
              set:
                X-Service: dft
