---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: dft
  namespace: rcfta
  labels:
    app: dft
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: regexp:^0(\.[0-9]+){2} # 0.x.x...

spec:
  selector:
    matchLabels:
      app: dft
  template:
    metadata:
      labels:
        app: dft
    spec:
      containers:
      - name: app
        image: stevenxie/dft:0.1.0-9-g74fdc53
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_NAME
          value: dft
        - name: DB_USER
          value: rcfta
        - name: DB_HOST
          value: postgres-postgresql.default
        envFrom:
        - secretRef:
            name: dft
        ports:
        - name: http
          containerPort: 8000
        readinessProbe: &probe
          initialDelaySeconds: 35
          httpGet:
            path: /login/
            port: 8000
        livenessProbe: *probe
        resources:
          requests:
            cpu: 45m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 650Mi
