---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: drone
  namespace: drone
  labels:
    app.kubernetes.io/name: drone

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
  serviceName: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: drone
          image: drone/drone:1.0.1
          env:
            - name: DRONE_GITHUB_CLIENT_ID
              value: 37ff2e81d1b8916911f6
            - name: DRONE_SERVER_HOST
              value: ci.stevenxie.me
            - name: DRONE_SERVER_PROTO
              value: https
            - name: DRONE_USER_CREATE
              value: username:stevenxie,machine:false,admin:true
            - name: DRONE_AGENTS_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: drone
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          readinessProbe: &probe
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe: *probe
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
            limits:
              cpu: 25m
              memory: 75Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      nodeSelector:
        node-role.kubernetes.io/storage: storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: drone
  namespace: drone

spec:
  encryptedData:
    DRONE_GITHUB_CLIENT_SECRET: AgACvID49FFdzNpvKWQr5V5XvdgZLkTT35NUDwyNOyIfxhyB9/jDiUQwKFtnKV+EbcxYj220/J+f3IzYc1ZqVZ87LSnohwIUbLr3bFsF+2Qe60sxEiEA1yQUKfKqc+CD12IeKsMkTqneY1HFSnL1LiEK7hxhViL1Afs7rBtuPBALRmVN8NRmsTCmPNDk6QgurNFTUKqh4jZDqrNNnu8FxV1Pf6BLFhQoyuVbMlkKwtxNR14ONj07PkluTHDPE5fVSrHietg4vT8jXobia2J3PGN/eRRxMWLBUgkQspclyM0QNugPOYtM7XChVYFtYc/QUaaHOy3V8Lr1mUKDaSeG1uJJP+vRW1k5v2qY6hle3lvBQzTN8iRQByiVk1xyI0Nq3eXvtrJt7EujD6k7Koh2gjVA9p/8LL8n6Klluv9u4AfS7QiwfruK5FnQoRmK2AsWReZlAEeXQxpvBLNsCLKLVPu+UqT5CsNdjyZRn7cr8xgHBh/HT5hlcTNEpChynONl3tlhx+Y0XpgZHTTpI7ZlRx6TIiScvwSSJwz94ccjEbSpr/zGJvCfvv+zelQQ8wiy5gaIufg6LKQqEWJyPSZok46tr+ykm/Hyl+rW332FqJtgmODOxDqlRUzIXKPnq+NuTamM2GU89dcT/ITn9zU6ByMq1UHP+Qig4v5+c5gKDFRJBU/s/dOtJ4upik5C2wXY6dSNNMNFe7uu6lS61anT3zt6bQvJV5m19iDeW903FxvSlOlOMokdsEYH
    DRONE_RPC_SECRET: AgBbGl/Pcs18iu9HTWt+tWD4ncmFSX+w2xLe9Gwqehc843s42kuK5aInhpmof69lhBNEMBBBtChC/COHHPYkX3m2li7sPCVVl9K/kRLHRSXAs/M8gvUq+A4Kmpo8p45NP4u/B7sHUFrJnIB1Z/hQ6A1+sq2W0Qpj5djWK4EdVmk1JUvphWA+QnxVVZoVfvXe+rGDx9vHDhpM3fgw2i/fEvqp4bdKGaCIAWXjVwJ2Tjnwl9E8d2/baFv68WOgR/ogdBwGiS2eSUi9FfZTudD4v2Z/jthgUS2vHG28RrnN+li5g+jk6C0QDvOWSS3+l31KFRfofA60o/aDYZlNCII03AT/Ef1h/SpIklkXDe5+HLyR3o+npWfJsMV2PaF8NlJYvl83d8McSHGVULBltAzQ90v/bh+qiUBKaNDDostjMUuooRWCJXdPhcCe8uRntBmBr4mUyUV+PsH5vhXFFDtUJ4TYKuYRO15VBhRMNBD2QrN3mjXOPN529XGQI8KHAoEvyhMReMMHo1EJ7aumEiAdbpVfO5+yXzHJHC8mEXdKarMwQm4bm2QkfXvfbiRr9aOsIM2ntmBeDj5kTDyW/tygWEgaJ0bNJXWMDlYvj7DQdnkCXHiKq8tNeev3yK7J5+ZbnDbsfbqvFihiZ4r1aGKgr/Ve8npInoC8r2g4CoaCV0Z13RrUtDvJHhsg+d4QQh6LUkiQ+FLLSjxH9//qz6Kg/d4IyKmLWzC1nBQVDgr4OE/qpuTwylpKCwsbllQAl+z9z9tNyuL/fQSVD7HEZl7QxyI0

---

apiVersion: v1
kind: Service

metadata:
  name: drone
  namespace: drone
  labels:
    app.kubernetes.io/name: drone

spec:
  selector:
    app.kubernetes.io/name: drone
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: grpc

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: drone
  namespace: drone

spec:
  gateways:
    - primary.istio-system
    - secondary.istio-system
  hosts:
    - ci.stevenxie.me
    - ci.stevenxie.com
  http:
    - match:
        - authority:
            exact: ci.stevenxie.com
      redirect:
        authority: ci.stevenxie.me
    - route:
        - destination:
            host: drone
            port:
              number: 80
          headers:
            response:
              set:
                X-Service: drone
