---

apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: columbia-system

spec:
  description: Columbia's cluster systems.
  sourceRepos: ["https://github.com/stevenxie/columbia"]
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
