---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: builds.build.knative.dev
  labels:
    knative.dev/crd-install: "true"
  annotations:
    flux.weave.works/ignore: "true"

spec:
  group: build.knative.dev
  version: v1alpha1
  scope: Namespaced
  names:
    categories:
      - all
      - knative
    kind: Build
    plural: builds
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=="Succeeded")].status
      name: Succeeded
      type: string
    - JSONPath: .status.conditions[?(@.type=="Succeeded")].reason
      name: Reason
      type: string
    - JSONPath: .status.startTime
      name: StartTime
      type: date
    - JSONPath: .status.completionTime
      name: CompletionTime
      type: date
  subresources:
    status: {}
