web:
  image:
    tag: 0.1.0-14-g5aedcb9

  deployment:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0

  resources:
    limits:
      memory: 200Mi
