---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: api
  namespace: chalmers
  labels:
    app: api

spec:
  entryPoints: ["websecure"]
  routes:
    - match: Host(`api.chalmersproject.com`)
      kind: Rule
      services:
        - name: api
          port: 80
  tls:
    secretName: tls-chalmersproject-com
