---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: chalmers
  labels:
    app: api
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: glob:master-*
    filter.fluxcd.io/migrate: glob:master-*

spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: app
        image: chalmersproject/api:master-e12d32e
        envFrom:
        - configMapRef:
            name: api
        - secretRef:
            name: api
        ports:
        - name: http
          containerPort: 80
        readinessProbe: &probe
          initialDelaySeconds: 5
          httpGet:
            path: /healthz
            port: http
        livenessProbe: *probe
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
          limits:
            cpu: 150m
            memory: 150Mi
      initContainers:
      - name: migrate
        image: chalmersproject/api:master-e12d32e
        args: ["migrate"]
        envFrom:
        - configMapRef:
            name: api
        - secretRef:
            name: api
