---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy

metadata:
  name: traefik
  namespace: default

spec:
  imageRepositoryRef:
    name: traefik
  policy:
    semver:
      range: "2"

