---

apiVersion: v1
kind: Service

metadata:
  name: http-debug
  namespace: default
  labels:
    app.kubernetes.io/name: http-debug
  annotations:
    flux.weave.works/ignore: "true"

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: http-debug
  ports:
    - name: http
      protocol: TCP
      port: 80
