---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: postgres
  namespace: default
  annotations:
    flux.weave.works/ignore: "true"
    flux.weave.works/automated: "true"
    flux.weave.works/chart-image: semver:~11

spec:
  releaseName: postgres
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: postgresql
    version: 3.15.0
  values:
    image:
      tag: "11"
    postgresqlUsername: admin
    postgresqlDatabase: self
    persistence:
      size: 4Gi
    metrics:
      enabled: true
      image:
        tag: "v0.4.7"
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9187"
