---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: dft
  namespace: rcfta
  labels:
    app: dft
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/app: regexp:^0(\.[0-9]+){2} # 0.x.x...

spec:
  selector:
    matchLabels:
      app: dft
  template:
    metadata:
      labels:
        app: dft
    spec:
      containers:
      - name: app
        image: stevenxie/dft:0.1.0-78-gcec170f
        envFrom:
        - configMapRef:
            name: dft
        - secretRef:
            name: dft
        ports:
        - name: http
          containerPort: 8000
        readinessProbe: &probe
          initialDelaySeconds: 30
          httpGet:
            path: /login/
            port: 8000
            httpHeaders:
              - name: Host
                value: localhost
        livenessProbe: *probe
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 500Mi
