---

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: istio-init
  namespace: argocd
  finalizers: ["resources-finalizer.argocd.argoproj.io"]

spec:
  project: columbia-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true

  source:
    repoURL: https://github.com/stevenxie/columbia
    targetRevision: argo
    path: workloads/istio-system/istio-init
