---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: istio-init
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
  labels:
    app.kubernetes.io/name: istio-init

spec:
  releaseName: istio-init
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.1.2/charts
    name: istio-init
    version: 1.1.2
