---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
  labels:
    app.kubernetes.io/name: istio

spec:
  releaseName: istio
  chart:
    repository: https://raw.githubusercontent.com/stevenxie/helm-charts/master
    name: istio
    version: 1.1.2-custom-1
  values:
    # Enabled components.
    pilot:
      autoscaleEnabled: false
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
    gateways:
      istio-ingressgateway:
        type: ClusterIP
        sds:
          enabled: true
        autoscaleEnabled: false
        env: {}
        ports:
          - name: http2
            port: 80
            targetPort: 80
            hostPort: 80
          - name: https
            port: 443
            hostPort: 443
          - name: status-port
            port: 15020
            targetPort: 15020
        meshExpansionPorts: []
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 250m
            memory: 125Mi
        nodeSelector:
          node-role.kubernetes.io/entrypoint: entrypoint

    # Disabled components.
    mixer:
      enabled: false
      policy:
        enabled: false
      telemetry:
        enabled: false
    prometheus:
      enabled: false

    # Common settings.
    global:
      useMCP: false
      proxy:
        # Sets the destination Statsd in envoy (the value of the
        # "--statsdUdpAddress" proxy argument would be <host>:<port>).
        # Disabled by default.
        # The istio-statsd-prom-bridge is deprecated and should not be used
        # moving forward.
        envoyStatsd:
          # If enabled is set to true, host and port must also be provided.
          # Istio no longer provides a statsd collector.
          enabled: false
          host: # example: statsd-svc.istio-system
          port: # example: 9125

        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 256m
            memory: 128Mi

