---

apiVersion: v1
kind: ConfigMap

metadata:
  name: coredns
  namespace: kube-system

data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }

    # Proxy .global services to istiocoredns (disabled).
    # global:53 {
    #     errors
    #     cache 30
    #     proxy . 10.245.49.23
    # }
