---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: regexp:^v0(\.[0-9]+){2}$
  labels:
    app.kubernetes.io/name: metrics-server

spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.6.0
  values:
    image:
      repository: gcr.io/google_containers/metrics-server-amd64
      tag: v0.3.2
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 100m
        memory: 100Mi

