---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: regexp:^v0(\.[0-9]+){2}$
  labels:
    app: metrics-server

spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.8.8
  values:
    image:
      repository: gcr.io/google_containers/metrics-server-amd64
      tag: v0.3.6
    args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
    resources:
      requests:
        cpu: 10m
        memory: 25Mi
      limits:
        cpu: 100m
        memory: 125Mi
