---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.7
  labels:
    app.kubernetes.io/name: sealed-secrets

spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.0.2
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.7.0
