---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regexp:v0\.12\.[0-9]+
  labels:
    app: sealed-secrets

spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.5.0
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.12.4-691254058-linux-arm
