---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    flucd.io/chart-image: semver:~0.9
  labels:
    app: sealed-secrets

spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.4.3
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.9.1
