apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: weave-scope
  labels:
    app.kubernetes.io/name: weave-scope

roleRef:
  kind: ClusterRole
  name: weave-scope
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: weave-scope
    namespace: weave-system
