---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: api-v4
  namespace: stevenxie
  labels:
    app: api
    version: v4

spec:
  entryPoints: ["websecure"]
  routes:
    - match: Host(`api.stevenxie.me`) && Path(`/v4`)
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: api-v4-redirect
    - match: Host(`api.stevenxie.me`) && PathPrefix(`/v4/`)
      kind: Rule
      services:
        - name: api-v4
          port: 80
      middlewares:
        - name: api-v4-cors
        - name: api-v4-strip-prefix
  tls:
    secretName: tls-stevenxie-me

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: api-v4-redirect
  namespace: stevenxie
  labels:
    app: api
    version: v4

spec:
  redirectRegex:
    regex: ^https://api.stevenxie.me/v4$
    replacement: https://api.stevenxie.me/v4/

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: api-v4-cors
  namespace: stevenxie
  labels:
    app: api
    version: v4

spec:
  headers:
    accessControlMaxAge: 5
    accessControlAllowHeaders:
      - Content-Type
    accessControlAllowMethods:
      - POST
    accessControlAllowOriginList:
      - https://stevenxie.me
    addVaryHeader: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: api-v4-strip-prefix
  namespace: stevenxie
  labels:
    app: api
    version: v4

spec:
  stripPrefix:
    prefixes:
      - /v4
