---

apiVersion: v1
kind: ConfigMap

metadata:
  name: api-v4
  namespace: stevenxie
  labels:
    app: api
    version: v4

data:
  API_CONTACT_FIRST_NAME: Steven
  API_CONTACT_LAST_NAME: Xie
  API_CONTACT_ABOUT: I'm a real human being.

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: api-v4
  namespace: stevenxie

spec:
  template:
    metadata:
      name: api-v4
      namespace: stevenxie
  encryptedData:
    API_CONTACT_BIRTHDAY: AgB8hr12hL0bjBzi1iyOK9tP22YJ4BIAulO5OueDGBgg73lvpUoxDPUGJUxY9YI98hmhZeQTc+U7io3cD7lzOZ3JxxmrA+4cVFgI7nuOBun1+8+oAXumpMmmheIfEbja//gQmAIW+e08cL07gKDAKPRGxNx2xHlxbIlyHnbthVnfUjUEIjDSNAXXIJYltB3JiaxhqsKyiiJQo/PNptSs/Oc7Bi611FJiTe2dcGznkTKq4PcotdMGS8y2uzdAaWe387sbPXSUalXPcBYnPf0wn0lD9JwyVmp091Jz8LCoiEjdLBp6GTLM0rqjIyBU8FAZoXSgn3lVjnyVEASqWV9yQROxVfahdK05HXXvm3K9FOvZgasjidIL+9bShwcJY10aeFPokQLADTsbrWOzEwtJw11s0ECajC8NUml7TD3nLvKt6dmPCHsbMRbrnxzd1YO6bMDbFtJWS11xQDZtZLIT76fHblGVZXnI5oG3xkJGMg+HYYDRFeEVu+QNkOubaAusjf3GCJCoeBkO8COPosBSttY3/MA7dE5qFG9bu5LcKPJKiNzab9Dwe0cWvqEmWOMhJbERSGyU5VQOhxwk/oYK6h6R50zW2rnGsqshgYEGSqHtwJywApyzgCa0TpeOHF92bJ2o3Zx0paxcR+Qu4E9acSb7CrE+Gssu+vlEK9YNOwTlbHM+BnIhz4G0dNgy59U9GNvlEOPjUujcC3Gt
    API_CONTACT_EMAIL: AgAli+S4AdjHEKRytbVsx3GleM9W5MlzhuGGnUqLcphbRRLYBM3E53eL49G2KKZ9k8KRVfWoruzOTYAgtmL09JwB64TNYTTArcQiF8JaY7D547CGSfabSslhfi/++Sf+LMB5gi3oYTGIdK65xXAjum6YQg3na21TtE+VnQHZ3netN1yTIFyGujYZk31nWRWmB/emlxfyovxbhyqXsS65nFoopNzddi95dPp5CVvTiM2OQUV1v+nJaLV5YjwSbpP9oInE//UAxMlahI2Fzy6k/nX0L7yWzbjUE1OTRfTa4XfMngGuPjNniR0fP0JdNe8fAVEaZlLZQ2forQ7XTXKPxPDfhtXXsykSd941X6IIck6d4Xf5NqAIlyk2H9bOvjgiY+DqqMk6LYQ+iuiuiNlJpHf7vplmRS3zuBqvfQAt/uSqPlKsX9wTydlPnVu0Rc6yB3nH8G1CQdzbnO6QJfVz1NQrNJJKrs/1ugZvIqAi7qJtAW/tclnGCGcS0KAXFsiFTBscVGZG90Bl+0S0evnM2hBmYFVw+rzVJOclr9cGojJ1DUtvSvHvXPLZoaYVEKrOXGwvN+c50/XHTwY9xAn2FzRE4z5OfWuHfgSKHRl9maDxcIk8La8xdg+ctg3oz68riuQtzyzzUWhyJq6x7oq3aSMckDFKhA0yNBG1buBievsv9I3zepLNT4g17AkjJTsggLsxbnxnRWbXr1sVlgJcng5k
    API_POSTGRES_URL: AgB5VfAQKQFG3DKAEsHF/zosN2k0bCmd/vhtwc9i/451kecElyZVgM1eEIsKaKoCo5YQGxSb9fNoTJx+BLENyraMBmFzvLmHbyzq9lutcZ+d+I4MIscvO1cb6rYso3/YDn1FxvtF0emt52j8phl8QocH6+Ii4dL5GlbBxKG5k1IT0pTLKkY3ivVrSZNdtVpsQ3aGO2PqG+p0ld0oeipEzxnxAAi2Q8SSHPAlY44G/HFKCdZwFxvGjzu/n1G5Ze2bcEzCOKDCrLvzsqfl2JJTh9i0ood6qpL7gDto0+mnE/HGF8Zl2Uu+LKeJLBdp16P3R/SoXczwtAF7+aMG5JxidalwwyCNstvepgNc3o/7LxBJPPjQVBsG50C8WZE1TvQgvWoJxTl/RcM/UbI80kUCpncLlp3o6fxty4Pi5IhjNwIgYRmuztQ3+Dju+tS+dbb22j1K+CuxJoJt9WkXSFsGMKZhbJ+h4aGubCkGmJEoCKX4I2z1VPzR3dl5B2B3puRtCxLameLqtziI2c+9kFyVyAAEVSfS1fINiaMD1TuWiMjK1fWitQh4MzHq5qxDw0hfZdbcj2s5rQLFV6WDj31gniBSJmrwWH0KcuVDmk18iDK+43ORE/FnshXqx0oefdnvSt+GuDDvNZMfdpb22ehrGLQi6syslkjmMO5t5IwVLV/jhqB+lgBaHwJGP790X5a25qIVtSgbiSToW4Db+5k6kybZVxNsuylbL4N1OPs/lEn0wbOBuO/Lm5scxJ7OlIf7/ZAfvgQcAgYnnzawlTFKTAQ3pBb4awQlgLDhG6W1KUvP/psarK24GcAhUozOWgu7WCpeWxEc17IjXkJjtThgWM6NQgEBEH+bn1BOqMg=
