---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lattice-api
  namespace: stevenxie
  labels:
    app: lattice
    component: api

spec:
  template:
    metadata:
      name: lattice-api
      namespace: stevenxie
  encryptedData:
    LATTICE_FIREBASE_ID: AgCnd+kr4mPNNDqZ1iq9PJCEahzbmO7zdUhxTiAcRQWf3Sf2+M+PJEOvMl3iXEYsXgfA9FlusBDfyEYbMSD/FYF5K0we3ACN8V+sclcNe+24jkh60mBn8tdmoWxOxBg07nrjz7i5t6pHcROn5YUD2w9Y0417HxCpQjYowaWwRoGS9Dms6gUXfJyBzuD2Csi+gR+dktprdK6lSF+O+lcuLLVy3Qm3d2Esu+N5cYJ4bUjCS89Ih0/XDXuc3jPw0ErfohEqGDwxnfEs3FhtKSecFjXKcT3UIZJ8ByjD7oaNoB43pQDaMlgJ1ZDWkHpwhMfqU4BAEBh2uzyKAoGMoLoCs69iqM6fBFwtJ9hvE1ZIQ/4dsObXDM5VCYkPbC4VGJLP9lNt5tE69IkYNckgeu3d4VexzTi/xb+bnw+G1edR0oebCzMlzd4zu7dwJyk/NnLRxDNiRxNV0WmjBoZgN7LmoB/533L34ryBc1jGnBKiOcBFYLjgsrd0PpXO3HvmhkneTo4Hh4zLIGE9vUdvgZ74KfMcqyjB9Ph0KWVo3B6LDcZ4eYcMjHSsn0bOvofr72bPvgi0GAc+XVZk80SlXzXYNi/K+8vopOG4vLDU37lmSOu1n6Qg2sQ1LdbjdqngJo+S+hO7isaWuOXc691r1jHzjXSqWI+eFbiVLutQ8FY90slLZUsPtidGdLMcuGvi1vtbR/D2kiHhkRMgs5mXMTco
    LATTICE_DATABASE_URI: AgDNIg2jtSFoT3LLtbILI7ScUJyBjaQMLHopBK2SNos0YY9bJnDz2S+zd7cpq0PS+FawRlExqiLIAHytZO2s7RZbuITD2fLLGlTyiSZ5pqTKml4oHZGMSw9KbxBZQu+D+Ta4/xvAzJDcf6ekYVRUkcDM0kA8zuhsaWv9JRbJLMXwAgt4HwtkzzwRh8oPkWpn9cAGtrEET8tRWwD31pfEk+wBSgHWh2RH67g+hqpdzKsykz6PcsKPP1iy4pexjMF6R2gQv0kWSXXr+pekFy4RRr9DyRkfEBgvElFKjet/YDXgg0ywgn9wRis4quXo4g/fjcqmEtaEFFcNvTAyqhD9uBz22dYvySR29IOIn0DmTk0X/f671dgG4azQ40M8LovS0dxe7qpOng+W9LEjRi/hpXptx8xdDpp89PtVN2gPGE4MmPNrbWtLL7jIktvnMBup+/zOMqproWHrb6kfsz7pKegjf6axTRV1VNn8z/GBgnSXGwdhl6KS2mEzhWgaiLnNKKoZ/edKMPH4hL8faDmSWdwM/EVGVev3dmNx+/CLlXf/dw1sY3B0LWBz/PMvEVo2bABkjBpq0MvJU28YyvA7vky081ptYfotE2p7bynprA3XK26kGPqquRnNw5Ed5skcsHSJ7XB4EqirMQJ5lkrn7lM6r8ujh23Q8B+e7e4rwWjjLujTD3kQDoi0UiRXApSEwFj14hMVJ80uzrs7wyjpiW5XGvsKWehq7XOAHZTQb7l0T8Gnro7ob2/sx2E1wPTaRgMd3RNGg6uRoh6BZgUcOW1/6VPS2M+6orYLUHY4QMKh6IjUEB1ebZg1B2/me9ppKnFqqnUNjFw=
