---

apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: lattice-uwblueprint-org
  namespace: stevenxie

spec:
  secretName: tls-lattice-uwblueprint-org
  dnsNames:
    - lattice.uwblueprint.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
