---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy

metadata:
  name: knative-build
  annotations:
    flux.weave.works/ignore: "true'"

spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - max: 65535
        min: 1
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  volumes:
    - configMap
    - secret
