---

apiVersion: fission.io/v1
kind: Environment

metadata:
  name: go
  namespace: default

spec:
  TerminationGracePeriod: 360
  version: 3
  builder:
    command: build
    image: fission/go-builder
  runtime:
    image: fission/go-env
  keeparchive: false
  poolsize: 2
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 1m
      memory: 1Mi
