---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: certificates.networking.internal.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
  group: networking.internal.knative.dev
  names:
    categories:
      - all
      - knative-internal
      - networking
    kind: Certificate
    plural: certificates
    shortNames: ["kcert"]
    singular: certificate
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: clusteringresses.networking.internal.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
  group: networking.internal.knative.dev
  names:
    categories:
      - all
      - knative-internal
      - networking
    kind: ClusterIngress
    plural: clusteringresses
    singular: clusteringress
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: configurations.serving.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.latestCreatedRevisionName
      name: LatestCreated
      type: string
    - JSONPath: .status.latestReadyRevisionName
      name: LatestReady
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
  group: serving.knative.dev
  names:
    categories:
      - all
      - knative
      - serving
    kind: Configuration
    plural: configurations
    shortNames:
      - config
      - cfg
    singular: configuration
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: helmreleases.flux.weave.works
  labels:
    app.kubernetes.io/name: flux

spec:
  group: flux.weave.works
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    shortNames: ['hr']
  scope: Namespaced
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ['chart']
          properties:
            releaseName:
              type: string
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
            timeout:
              type: integer
              format: int64
            resetValues:
              type: boolean
            forceUpgrade:
              type: boolean
            valueFileSecrets:
              type: array
              items:
                type: object
                required: ['name']
                properties:
                  name:
                    type: string
            valuesFrom:
              type: array
              items:
                type: object
                properties:
                  configMapKeyRef:
                    type: object
                    required: ['name']
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                      optional:
                        type: boolean
                  secretKeyRef:
                    type: object
                    required: ['name']
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                      optional:
                        type: boolean
                  externalSourceRef:
                    type: object
                    required: ['url']
                    properties:
                      url:
                        type: string
                      optional:
                        type: boolean
                oneOf:
                  - required: ['configMapKeyRef']
                  - required: ['secretKeyRef']
                  - required: ['externalSourceRef']
            values:
              type: object
            chart:
              oneOf:
                - required: ['git', 'path']
                  properties:
                    git:
                      type: string
                      format: git # not defined by OAS
                    path:
                      type: string
                    ref:
                      type: string
                    skipDepUpdate:
                      type: boolean
                - required: ['repository', 'name', 'version']
                  properties:
                    repository:
                      type: string
                      format: url # not defined by OAS
                    name:
                      type: string
                    version:
                      type: string
                      format: semver # not defined by OAS
                    chartPullSecret:
                      properties:
                        name:
                          type: string

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: images.caching.internal.knative.dev
  labels:
    knative.dev/crd-install: "true"

spec:
  group: caching.internal.knative.dev
  names:
    categories:
      - all
      - knative-internal
      - caching
    kind: Image
    plural: images
    shortNames: ["img"]
    singular: image
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: podautoscalers.autoscaling.internal.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
  group: autoscaling.internal.knative.dev
  names:
    categories:
      - all
      - knative-internal
      - autoscaling
    kind: PodAutoscaler
    plural: podautoscalers
    shortNames: ["kpa"]
    singular: podautoscaler
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: revisions.serving.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.serviceName
      name: Service Name
      type: string
    - JSONPath: .metadata.labels['serving\.knative\.dev/configurationGeneration']
      name: Generation
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
  group: serving.knative.dev
  names:
    categories:
      - all
      - knative
      - serving
    kind: Revision
    plural: revisions
    shortNames: ["rev"]
    singular: revision
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: routes.serving.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.domain
      name: Domain
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
  group: serving.knative.dev
  names:
    categories:
      - all
      - knative
      - serving
    kind: Route
    plural: routes
    shortNames: ["rt"]
    singular: route
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: serverlessservices.networking.internal.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  group: networking.internal.knative.dev
  names:
    categories:
      - all
      - knative-internal
      - networking
    kind: ServerlessService
    plural: serverlessservices
    shortNames: ["sks"]
    singular: serverlessservice
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: services.serving.knative.dev
  labels:
    knative.dev/crd-install: "true"
    serving.knative.dev/release: devel

spec:
  additionalPrinterColumns:
    - JSONPath: .status.domain
      name: Domain
      type: string
    - JSONPath: .status.latestCreatedRevisionName
      name: LatestCreated
      type: string
    - JSONPath: .status.latestReadyRevisionName
      name: LatestReady
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].status
      name: Ready
      type: string
    - JSONPath: .status.conditions[?(@.type=='Ready')].reason
      name: Reason
      type: string
  group: serving.knative.dev
  names:
    categories:
      - all
      - knative
      - serving
    kind: Service
    plural: services
    shortNames:
      - kservice
      - ksvc
    singular: service
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
