---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: controller
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.controller: regexp:^0\.5\.[0-9]+$ # 0.5.x

spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: gcr.io/knative-releases/github.com/knative/serving/cmd/controller:v0.5.1
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: metrics
          containerPort: 9090
        resources:
          requests:
            cpu: 75m
            memory: 75Mi
          limits:
            cpu: 300m
            memory: 300Mi
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
      volumes:
      - name: config-logging
        configMap:
          name: config-logging
---

apiVersion: v1
kind: ConfigMap

metadata:
  name: config-controller
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel

data:
  queueSidecarImage: gcr.io/knative-releases/github.com/knative/serving/cmd/queue:v0.5.1
  _example: |
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this block and unindented to actually change the configuration.

    # List of repositories for which tag to digest resolving should be skipped
    registriesSkippingTagResolving: "ko.local,dev.local"

---

apiVersion: v1
kind: Service

metadata:
  name: controller
  namespace: knative-serving
  labels:
    app: controller
    serving.knative.dev/release: devel

spec:
  selector:
    app: controller
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
