---

apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image

metadata:
  name: queue-proxy
  namespace: knative-serving
  labels:
    serving.knative.dev/release: devel

spec:
  image: gcr.io/knative-releases/github.com/knative/serving/cmd/queue@sha256:b5c759e4ea6f36ae4498c1ec794653920345b9ad7492731fb1d6087e3b95dc43
