---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cloudflare
  namespace: cert-manager

spec:
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
  encryptedData:
    apiKey: AgBW+JWj9R8+8pN0tuXhM9Gl/ZSwh1iOfklsTBRlIqSjkCpL5KLTlWrjNW8XgYH6CW42YjsSS0+oJK0JstU4YdxWsjRxn9+3cooAOQovnEe+xeJZcQR29NZGqNyF2k0NO5xlmF6fRTVsKvcnnAWOGy18kotXPwyYRNDVlhrLSKZY8U7xz59k87CURjiR5kQpVJPivBkTTGIZKGH2OcIJQmxdofGWqOAPx6YbuZgUtN0Da3FkWD6HZef+LQjTHs1R/CBhkUjkFXqUnmTRn7RzeBmaq1kq0CcWmEU4PbqYxe8SmqkVc8r7Sp3CUDvTTJXQub2iYnCqlR/QQgWvoYKhRRwqskoMEaN1RueupF9ejtfpHXZiBx7c6uhQq7hh0uvaVwBwV1/RiDuNmd0LY7qx72QSpM11pwCFxANqgUhITK12xG+XZmkIwH2WgnsLgETravVwoguXF+vhVk1Y8uwZ7k2ku9ZjNJ75sMUiXazuBL6hwS/1OgsdjdFZyfHFZ20FmEkF781sobSTLFi5P5+49+82emIE9NP3hlZmvhBSjInAHIa6t/0WEeqoMwHMo9det3IE+3MthlfiSyH9WxtmEJVttfVwocU2b63KHWbqInN9MQHflRdI3A9R7SMl6cqCtj9LjKw7DoqgYNF/OR8iFInGtrk4FVPxqQHwY+ribKEYtHzk1UJJL0hacJMjDD6ku+SeYA7/L+lwbXbe7EgWlscwhvkMn8/Ve051HEPrYKindc3oTz4A
