---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: ambassador
  namespace: gateway
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.53
  labels:
    app.kubernetes.io/name: ambassador

spec:
  releaseName: ambassador
  chart:
    repository: https://raw.githubusercontent.com/stevenxie/helm-charts/master/
    name: ambassador
    version: 2.3.0
  values:
    replicaCount: 1
    image:
      repository: quay.io/datawire/ambassador
      tag: 0.53.1

    service:
      type: ClusterIP
      http:
        hostPort: 80
      https:
        hostPort: 443
      annotations:
        getambassador.io/config: |
          apiVersion: ambassador/v1
          kind: Module
          name: ambassador
          config:
            service_port: 8443

    ## Allow pod to use host network (elevate privileges).
    securityContext:
      runAsUser: 0

    deployment:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 250Mi

    nodeSelector:
      node-role.kubernetes.io/entrypoint: entrypoint
