---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: cloudflare
  namespace: gateway

spec:
  encryptedData:
    apiKey: AgBrLEbr+wcqZxsgPbUHBPoAWHQeahdyayjc+ZU7NjxiDVxM2nkUB3W3n+k72Wvrrjgw7Jpeez/igPng9Cijjj64MdU7ZgwkyruRj2RNpp/vfI5HiNbThe+f8QJ9NBOZnDd6PT7MCvlyihhzAP0bTdte5UKBTP9glFSB6TCL4moJSRMU9oFkLDl8GPKtJeDaX7Hn3U/shq0xfAA7V8Ld2zSTEc3zSOOErqImUPmuxre6gFGaqXhie/UG3Lf+QfWKKmK3JDUeTkxVMXL2iIZL108bALOZ0wc6gKpBeMa9LuRerZQ6HQiz9M0Oe2ThtrEFctWsAaIrkr9RlMfRSV4wbh23l5RCkyC1kusny6K8bR4Y5c2HhYWWUt4NDi3L+a0oyNKYMUIl75lbMBHxQ9QEIj7LHYOrOg6uNz+KVbKsNXKeeVJ3gsqyuAInIfpoF6P1K6Zm1FPXlzROniflO72AR7NQ4lUwWkWrrMxtLj5/hZm3rmgNkSfKI3Z85iki5uHlgk85nbmQcy/pLa9hVTT0268TW7fAf/e6NiFV6gt6VpA/C9bqrTryxU77GVGJq4zF8RtioU1oXGCgtFm29bGTqExNL38JpTHQMqQ2JV5pEmOy8bjfwJPVhDXT+4jS9ZZh/4D3g7SeEzgj5BNC4fcpD7BKaz/3mVchvXtplaCtLMsE8nWL0MV4i5t7R7QWie3gxjq4meQIPrleCb0DWemqCsiaU+CCa6pzIPuQXpaS726GSTylcLaX

