---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer

metadata:
  name: letsencrypt-prod
  namespace: gateway

spec:
  acme:
    email: hello@stevenxie.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: cloudflare
          cloudflare:
            email: steven.xie@outlook.com
            apiKeySecretRef:
              name: cloudflare
              key: apiKey
