---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate

metadata:
  name: stevenxie-me
  namespace: gateway

spec:
  secretName: stevenxie-me-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: stevenxie.me
  dnsNames: &names
    - stevenxie.me
    - "*.stevenxie.me"
  acme:
    config:
      - dns01:
          provider: cloudflare
        domains: *names
