---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: drone
  namespace: drone
  labels:
    app: drone

spec:
  metadata:
    name: drone
    namespace: drone
    labels:
      app: drone

  encryptedData:
    DRONE_GITHUB_CLIENT_SECRET: AgBWKb+u+kMEftiCJ9+wgtyahFVCppAysOqcpWm0JHZKpoZzlEpJHUojEsMrJNioLVY3sDgoUmCtQMALQf7wIc2N0SjwdY9hwTlmv7M4mbkNYoZT/YUFLfHqD7hu2CWGzukHis4smetGinhRJyPdpgurYQHxKpPauSojPsXrAEvvG3trfHzVHzWIK1Cq5BtuQdfLqkoznjK7YImMbUwOxKUg/3+dubXb3YkZ4KujehqOZPNw7bePf0tCoJ+9rJVTOvE1AutL5urgw6w1CKGpJbB8eIIw2DxABk3fAkeAblCJRiB3TZ1KOIpp9e7ZQhZ56BefiSRwMI2Qh+a8J+I3zRdy2SwSfhuVFmoVUSfHZdL3U/9QI2Pn5fMUmS6WsPQrs4+15sZ2eMqs8XQZpZZMv9o9Nmh+4YHsdRzoUu9qytx+n8l/RnTv7KSDAYn3TRocYwtffOewmYAwHAALHf1ijEs+1+dXFbeR+m4en1FDCVTwhljZtD63Z2+bbOUfsQ18IA+uzyB9c4bNwbGHiiNXxE+quHN93sbh5nL4cyl7dUKPf1BaOkU1+z4Dtgs/zYyxDNVXrRrrrXEZadHoIqAXIeAkpzd+XPVCmYxMaAUz+J38O3AC5UW4sjX5SAU5o4UwDDmpGtAhsV8ewiWzvdadq3p/4HEpc472Iox2CiybiZu9hSdbv00ee3PoprkVjEfNlaDWnwwKqKYnOCGdPhqEzg/bLz1vuAxxLiMGekiGfppwOLbfFfAfMEwC
    DRONE_RPC_SECRET: AgBFkFyf5sPG6bgF+eWtHjYpKEpUxtoc/roMV46AhL78GhnsslSh8zNZH6qOWTqYVYHS5mnxsGfywkuYq4pDp4Y1QJ43vTmHapV3iN0TVgL6oD6y0YSyD640q0ghIJ2c7AXk+d912v6HogbtmbGhCOCCQ7L7GwEiAhf3CLSEzoaNVmAyzENYyR+lhccI1jG+PEJAQoygb/V0OGoGR/B9l1VLvnrNMYeol19/nyk9zsVSGtl1pb7rEddxoMzZ2srwR8Qz9+XTKFpQ4WZihVFACxOtRoXlE1uc/FHpONF75Hoi582LmNwIWNnuDIyc3FXKS/y/zicDbxfYYlFluzi66J3W60xr6alFQ+d6lb2wBjocD/3hxDizJDaJYh9exNvW+tX8k9fswrA/a6Q4U2efzDmkrYDm7vgdquyDQeFIxcKPjuKGVObHqTM8FBKr8Ife/XXl8MpjCNmefetxWdSReboJXDbUYM6S4qyYdzEWBBmslxszgoWroUFqx65L7IkBAovlmRAZBc/+eZiXEty5H6HvHll3WQH49OqsOXE4Z+rQVPHMm0LF/GQDr1MEeHPPN6786Rk0xzc3geEHgVY7hYCxl4AyzNh+V6hWQO/Xnp116istLj4kWmnly9KCghkz+moOTwPXm+mWqobrKHw+wELvQ11ZAJp51OQpJeMY/6Z7xuVApfY/rCZOabT4PeWP+c7ZhxMlBlwQRGulBkBZb6XTAUdfVSRPwvoc5QmAee8JlFk4oF+1Kdy2s3K29Ne7/+RZrd18u7Rwj3pnOc+PZdun
