---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: drone
  namespace: drone
  labels:
    app: drone

spec:
  encryptedData:
    DRONE_GITHUB_CLIENT_SECRET: AgACvID49FFdzNpvKWQr5V5XvdgZLkTT35NUDwyNOyIfxhyB9/jDiUQwKFtnKV+EbcxYj220/J+f3IzYc1ZqVZ87LSnohwIUbLr3bFsF+2Qe60sxEiEA1yQUKfKqc+CD12IeKsMkTqneY1HFSnL1LiEK7hxhViL1Afs7rBtuPBALRmVN8NRmsTCmPNDk6QgurNFTUKqh4jZDqrNNnu8FxV1Pf6BLFhQoyuVbMlkKwtxNR14ONj07PkluTHDPE5fVSrHietg4vT8jXobia2J3PGN/eRRxMWLBUgkQspclyM0QNugPOYtM7XChVYFtYc/QUaaHOy3V8Lr1mUKDaSeG1uJJP+vRW1k5v2qY6hle3lvBQzTN8iRQByiVk1xyI0Nq3eXvtrJt7EujD6k7Koh2gjVA9p/8LL8n6Klluv9u4AfS7QiwfruK5FnQoRmK2AsWReZlAEeXQxpvBLNsCLKLVPu+UqT5CsNdjyZRn7cr8xgHBh/HT5hlcTNEpChynONl3tlhx+Y0XpgZHTTpI7ZlRx6TIiScvwSSJwz94ccjEbSpr/zGJvCfvv+zelQQ8wiy5gaIufg6LKQqEWJyPSZok46tr+ykm/Hyl+rW332FqJtgmODOxDqlRUzIXKPnq+NuTamM2GU89dcT/ITn9zU6ByMq1UHP+Qig4v5+c5gKDFRJBU/s/dOtJ4upik5C2wXY6dSNNMNFe7uu6lS61anT3zt6bQvJV5m19iDeW903FxvSlOlOMokdsEYH
    DRONE_RPC_SECRET: AgBbGl/Pcs18iu9HTWt+tWD4ncmFSX+w2xLe9Gwqehc843s42kuK5aInhpmof69lhBNEMBBBtChC/COHHPYkX3m2li7sPCVVl9K/kRLHRSXAs/M8gvUq+A4Kmpo8p45NP4u/B7sHUFrJnIB1Z/hQ6A1+sq2W0Qpj5djWK4EdVmk1JUvphWA+QnxVVZoVfvXe+rGDx9vHDhpM3fgw2i/fEvqp4bdKGaCIAWXjVwJ2Tjnwl9E8d2/baFv68WOgR/ogdBwGiS2eSUi9FfZTudD4v2Z/jthgUS2vHG28RrnN+li5g+jk6C0QDvOWSS3+l31KFRfofA60o/aDYZlNCII03AT/Ef1h/SpIklkXDe5+HLyR3o+npWfJsMV2PaF8NlJYvl83d8McSHGVULBltAzQ90v/bh+qiUBKaNDDostjMUuooRWCJXdPhcCe8uRntBmBr4mUyUV+PsH5vhXFFDtUJ4TYKuYRO15VBhRMNBD2QrN3mjXOPN529XGQI8KHAoEvyhMReMMHo1EJ7aumEiAdbpVfO5+yXzHJHC8mEXdKarMwQm4bm2QkfXvfbiRr9aOsIM2ntmBeDj5kTDyW/tygWEgaJ0bNJXWMDlYvj7DQdnkCXHiKq8tNeev3yK7J5+ZbnDbsfbqvFihiZ4r1aGKgr/Ve8npInoC8r2g4CoaCV0Z13RrUtDvJHhsg+d4QQh6LUkiQ+FLLSjxH9//qz6Kg/d4IyKmLWzC1nBQVDgr4OE/qpuTwylpKCwsbllQAl+z9z9tNyuL/fQSVD7HEZl7QxyI0
