---

apiVersion: v1
kind: Service

metadata:
  name: drone
  namespace: drone
  labels:
    app: drone

spec:
  selector:
    app.kubernetes.io/name: drone
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: drone
  namespace: drone
  labels:
    app: drone

spec:
  gateways:
    - stevenxie-me.istio-system
    - stevenxie-com.istio-system
  hosts:
    - ci.stevenxie.me
    - ci.stevenxie.com
  http:
    - match:
        - authority:
            exact: ci.stevenxie.com
      redirect:
        authority: ci.stevenxie.me
    - route:
        - destination:
            host: drone
            port:
              number: 80
          headers:
            response:
              set:
                X-Service: drone
