---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: drone
  namespace: drone
  labels:
    app.kubernetes.io/name: drone
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.drone: semver:~1.0

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
  serviceName: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: drone
          image: drone/drone:1.0.1
          env:
            - name: DRONE_GITHUB_CLIENT_ID
              value: 37ff2e81d1b8916911f6
            - name: DRONE_SERVER_HOST
              value: ci.stevenxie.me
            - name: DRONE_SERVER_PROTO
              value: https
            - name: DRONE_USER_CREATE
              value: username:stevenxie,machine:false,admin:true
            - name: DRONE_USER_FILTER
              value: stevenxie,DangAsian,tugolo
            - name: DRONE_AGENTS_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: drone
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          readinessProbe: &probe
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe: *probe
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
            limits:
              cpu: 25m
              memory: 75Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      nodeSelector:
        node-role.kubernetes.io/storage: storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
