---

apiVersion: v1
kind: Service

metadata:
  name: api-v2
  namespace: stevenxie
  labels:
    app: api
    version: v2

spec:
  selector:
    app: api
    version: v2
  ports:
    - name: graphql
      port: 80
      targetPort: graphql
    - name: debug
      port: 8080
      targetPort: debug
