---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: lattice-api
  namespace: stevenxie
  labels:
    app: lattice
    component: api

spec:
  template:
    metadata:
      name: lattice-api
      namespace: stevenxie
  encryptedData:
    LATTICE_FIREBASE_ID: AgCnd+kr4mPNNDqZ1iq9PJCEahzbmO7zdUhxTiAcRQWf3Sf2+M+PJEOvMl3iXEYsXgfA9FlusBDfyEYbMSD/FYF5K0we3ACN8V+sclcNe+24jkh60mBn8tdmoWxOxBg07nrjz7i5t6pHcROn5YUD2w9Y0417HxCpQjYowaWwRoGS9Dms6gUXfJyBzuD2Csi+gR+dktprdK6lSF+O+lcuLLVy3Qm3d2Esu+N5cYJ4bUjCS89Ih0/XDXuc3jPw0ErfohEqGDwxnfEs3FhtKSecFjXKcT3UIZJ8ByjD7oaNoB43pQDaMlgJ1ZDWkHpwhMfqU4BAEBh2uzyKAoGMoLoCs69iqM6fBFwtJ9hvE1ZIQ/4dsObXDM5VCYkPbC4VGJLP9lNt5tE69IkYNckgeu3d4VexzTi/xb+bnw+G1edR0oebCzMlzd4zu7dwJyk/NnLRxDNiRxNV0WmjBoZgN7LmoB/533L34ryBc1jGnBKiOcBFYLjgsrd0PpXO3HvmhkneTo4Hh4zLIGE9vUdvgZ74KfMcqyjB9Ph0KWVo3B6LDcZ4eYcMjHSsn0bOvofr72bPvgi0GAc+XVZk80SlXzXYNi/K+8vopOG4vLDU37lmSOu1n6Qg2sQ1LdbjdqngJo+S+hO7isaWuOXc691r1jHzjXSqWI+eFbiVLutQ8FY90slLZUsPtidGdLMcuGvi1vtbR/D2kiHhkRMgs5mXMTco
    LATTICE_DATABASE_URI: AgBO7At7EQ2GJf0wxTuDwiGryQzXEL4wkLZcQEuisPN4CJNn8PUWyzSR2aA/vYIkaE2V5SWl982yVgFsGeNkQI1OaAuiFS6UqF0Hh/jt8ll8u9rsie17ufyiCTk1Xa+jxaXEwIMrRcF8UEddhOcGu+MliZ7tME2zN970EN/DCxHyhCTuCkShgEEzh6VOWxnto1zOg3tPBiIud/RnMFVzMxCnsJxRQ+Zs1gsBI7PypkC0tKSdsrnmv9/wpbvvJaoIjN7U94B4AnhbhMCFTm4gJeGpsQiP+zns0L4j3P5KX5sj0ftHscY22Rim/9NJlHVYiY5/R85K4PwABOyEfTOpC+ob3aMa7+qdvMODDfOD25yhLBAd9SM9x58hjnOadoD+rRFLkSz6OV0YRrgY7D6vZKA2nCEkZU3q96bKhSl+dl1M8MxP6EcH8wWNQqIeUtt2lNAa+PsA93iOIcUamJbpR5Dz9KdnNmtwxObdckS8L+l08AmS+UWXiMbkYvAEd/dRDXyhezXY6GjMI/Dj9GpgWmL0czIPtS3A0pNKNw4Ckbr0zNmh/xWDIrRtL+S0bPZQVMDbrR0+VBhXKhWswbHbGXzx0WcnA52+tPVobrYpP6h4udQFv2FuGhEcKuseGnwOoWJ+TJ7gLlojdN4XHvb9SNZzQTkGtWio5l3evlKzDeKT1o5gjXoAltFZaiU6BTIu/K/9h+gQw2K6aP2oa3GFw7wB++TcAziVKGg5nB/Rd9MBKe1boIke8cVPgM/0JlTWoFKrCuJe13Msnh6XEeyGKEqh7KZR5EyiHILOrdXqyTxgNoLbavXHyEU4vLMcl3GgpKDtPd8=
