---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: build-controller-admin
  annotations:
    fluxcd.io/ignore: "true"

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-build-admin

subjects:
  - kind: ServiceAccount
    name: build-controller
    namespace: knative-build
