apiVersion: apps/v1
kind: Deployment

metadata:
  name: argocd-repo-server

spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          args:
            - --parallelismlimit
            - "1"
          resources:
            requests:
              memory: 80Mi
              cpu: 1m
            limits:
              memory: 200Mi
              cpu: 500m
