---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: deploy
  namespace: default
  annotations:
    flux.weave.works/ignore: "true"

rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - apps
      - deployments
      - replicasets
      - statefulsets
      - pods
    verbs:
      - patch
