git:
  url: git@github.com:stevenxie/columbia
  path: cluster,workloads

helmOperator:
  create: true
  createCRD: false
  tillerNamespace: helm
  tls:
    enable: true

memcached:
  tag: 1.5.12-alpine

prometheus:
  enabled: true
