---

apiVersion: ceph.rook.io/v1
kind: CephCluster

metadata:
  name: primary
  namespace: rook-ceph

spec:
  cephVersion:
    image: ceph/ceph:v13.2.5-20190410
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
    ssl: false
  mon:
    count: 3
    allowMultiplePerNode: true
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: ceph-primary-dashboard
  namespace: rook-ceph

spec:
  gateways: ["primary.istio-system"]
  hosts: ["ceph.stevenxie.me"]
  http:
    - route:
        - destination:
            host: rook-ceph-mgr-dashboard
