---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role

metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph

rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups: ["ceph.rook.io"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding

metadata:
  name: rook-ceph-mgr
  namespace: rook-ceph

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr

subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: rook-ceph

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - get
      - list
      - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr-system

subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgrs
    namespace: rook-ceph

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding

metadata:
  name: rook-ceph-mgr-cluster
  namespace: rook-ceph

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-cluster

subjects:
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: rook-ceph
