---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: rook-ceph-osd
  namespace: rook-ceph

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
  name: rook-ceph-osd
  namespace: rook-ceph

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
  name: rook-ceph-osd
  namespace: rook-ceph

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-osd

subjects:
  - kind: ServiceAccount
    name: rook-ceph-osd
    namespace: rook-ceph
