---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding

metadata:
  name: rook-ceph-cluster-mgmt
  namespace: rook-ceph

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-cluster-mgmt

subjects:
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph
