---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: api-v1
  namespace: default
  labels:
    app: api-v1
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.apisrv: regexp:^1(\.[0-9]+){2} # 1.x.x...

spec:
  selector:
    matchLabels:
      app: api-v1
  template:
    metadata:
      labels:
        app: api-v1
    spec:
      containers:
      - name: apisrv
        image: stevenxie/api:1.2.0-4-g403353c
        imagePullPolicy: IfNotPresent
        env:
        - name: GOENV
          value: production
        envFrom:
        - secretRef:
            name: api-v1
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /etc/api
        readinessProbe: &probe
          httpGet:
            path: /
            port: http
        livenessProbe: *probe
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: api-v1
