---

apiVersion: v1
kind: Service

metadata:
  name: api-v1
  namespace: default
  labels:
    app: api
    version: v1

spec:
  selector:
    app: api
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: api-v1
  namespace: default
  labels:
    app: api
    version: v1

spec:
  gateways: ["primary.istio-system"]
  hosts: ["api-origin.stevenxie.me"]
  http:
    # Enforce trailing slash.
    - match:
        - uri:
            exact: /v1
      redirect:
        uri: /v1/

    # Route traffic to 'api-v1'.
    - match:
        - uri:
            prefix: /v1/
      rewrite:
        uri: /
      route:
        - destination:
            host: api-v1
          headers:
            response:
              set:
                X-Service: api-v1-origin
