---

apiVersion: v1
kind: Service

metadata:
  name: api-v2
  namespace: default
  labels:
    app: api
    version: v2

spec:
  selector:
    app: api
    version: v2
  ports:
    - name: http-graphql
      port: 80
      targetPort: http-graphql
    - name: http-debug
      port: 6060
      targetPort: http-debug

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: api-v2
  namespace: default
  labels:
    app: api
    version: v2

spec:
  gateways: ["primary.istio-system"]
  hosts: ["api.stevenxie.me"]
  http:
    # Redirect root requests to GraphiQL.
    - match:
        - uri:
            exact: /
      redirect:
        uri: /v2/graphiql

    # Enforce trailing slash.
    - match:
        - uri:
            exact: /v2
      redirect:
        uri: /v2/

    # Short cache.
    - match:
        - uri:
            prefix: /v2/
      rewrite:
        uri: /
      route:
        - destination:
            host: api-v2
            port:
              number: 80
          headers:
            response:
              set:
                X-Service: api-v2
                Cache-Control: public, max-age=1
                Vary: Origin
      corsPolicy:
        allowOrigin: ["*"]
        allowHeaders: ["Content-Type"]
        allowMethods: ["POST"]
