---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: api-repo
  namespace: default

spec:
  gateways: ["primary.istio-system"]
  hosts: ["api.stevenxie.me"]
  http:
    - match:
        - uri:
            exact: /
      redirect:
        authority: github.com
        uri: /stevenxie/api
