---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: api-v2
  namespace: default
  labels:
    app: api
    version: v2
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.server: regexp:^2(\.[0-9]+){2} # 1.x.x...

spec:
  selector:
    matchLabels:
      app: api
      version: v2
  template:
    metadata:
      labels:
        app: api
        version: v2
    spec:
      containers:
      - name: server
        image: stevenxie/api:2.2.25
        imagePullPolicy: IfNotPresent
        command: ["server"]
        args: ["--shutdown-timeout", "5s", "--debug"]
        env:
        - name: GOENV
          value: production
        envFrom:
        - secretRef:
            name: api-v2
        ports:
        - name: graphql
          containerPort: 3000
        - name: debug
          containerPort: 6060
        volumeMounts:
        - name: config
          mountPath: /etc/api
        readinessProbe: &probe
          httpGet:
            path: /
            port: 3000
        livenessProbe: *probe
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: api-v2
