---

apiVersion: v1
kind: Service

metadata:
  name: api-v1
  namespace: default
  labels:
    app: api
    version: v1

spec:
  selector:
    app: api
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: api-v1
  namespace: default
  labels:
    app: api
    version: v1

spec:
  gateways:
    - primary.istio-system
    - cluster.istio-system
  hosts:
    - api-v1-origin.stevenxie.me
    - api-v1.default.svc.cluster.local
  http:
    # Short cache on '/'.
    - match:
        - uri:
            exact: /
      route:
        - destination: &destination
            host: api-v1
          headers:
            response:
              set:
                X-Service: &service api-v1
                Cache-Control: public, max-age=1

    # Short cache, disable grace on '/nowplaying/**/*'.
    - match:
        - uri:
            prefix: /nowplaying
      route:
        - destination: *destination
          headers:
            response:
              set:
                X-Service: *service
                X-No-Grace: "true"
                Cache-Control: public, max-age=1

    # No cache on '/location/history'.
    - match:
        - uri:
            exact: /location/history
      route:
        - destination: *destination
          headers:
            response:
              set:
                X-Service: *service
                Cache-Control: no-cache, no-store, must-revalidate
                Pragma: no-cache

    # Set a cache of 120s on all other rquests.
    - route:
        - destination: *destination
          headers:
            response:
              set:
                X-Service: *service
                Cache-Control: public, max-age=120
