---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: api
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: regexp:^0(\.[0-9]+){2} # 0.x.x...
  labels:
    app.kubernetes.io/name: api

spec:
  releaseName: api
  chart:
    repository: https://charts.stevenxie.me
    name: api
    version: 0.5.1
  valuesFrom:
  - secretKeyRef:
      name: api-release
  values:
    config:
      mongo:
        db: self
      airtable:
        baseId: appDm0Ts20KbQ0rG0
        moodSource:
          limit: 15
      jobserver:
        redisAddr: redis-master:6379
        fetchMoodsCron: 0 0-59/5 * * * *

    image:
      repository: stevenxie/api
      tag: 0.4.0-5-g2dabad1

    deployment:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

    jobserver:
      enabled: false
    jobserver-ui:
      enabled: false
