---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: api
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.apisrv: regexp:^1(\.[0-9]+){2} # 1.x.x...

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
      - name: apisrv
        image: stevenxie/api:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GOENV
          value: production
        envFrom:
        - secretRef:
            name: api
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /etc/api
        readinessProbe: &probe
          httpGet:
            path: /
            port: http
        livenessProbe: *probe
          # resources:
          #   requests:
          #     cpu: 25m
          #     memory: 25Mi
          #   limits:
          #     cpu: 100m
          #     memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: api
