---

apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: default
  labels:
    app: api

spec:
  selector:
    app: api
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: api
  namespace: default

spec:
  gateways: ["primary.istio-system"]
  hosts: ["api-origin.stevenxie.me"]
  http:
    - route:
        - destination:
            host: api
          headers:
            response:
              set:
                X-Service: api-origin
