---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: bincode
  namespace: default
  labels:
    app: bincode
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.server: regexp:^0(\.[0-9]+){2} # 1.x.x...

spec:
  selector:
    matchLabels:
      app: bincode
  template:
    metadata:
      labels:
        app: bincode
    spec:
      containers:
      - name: server
        image: stevenxie/bincode:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: GOENV
          value: production
        ports:
        - name: http
          containerPort: 3000
        readinessProbe: &probe
          httpGet:
            path: /
            port: http
        livenessProbe: *probe
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 50m
            memory: 50Mi
