---

apiVersion: v1
kind: Service

metadata:
  name: charts
  namespace: default
  labels:
    app.kubernetes.io/name: charts
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: charts
      service: https://stevenxie.github.io
      host: charts.stevenxie.me
      prefix: /

spec:
  type: ExternalName
  externalName: stevenxie.github.io
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
