---

apiVersion: v1
kind: Service

metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo

spec:
  type: ExternalName
  externalName: ds121871.mlab.com
  ports:
    - name: mongo
      protocol: TCP
      port: 21871
      targetPort: 21871
