apiVersion: v1
kind: LimitRange

metadata:
  name: overloadprotection
  namespace: default

spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        memory: 25Mi
