---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease

metadata:
  name: postgres
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: regexp:^11\.9\.([0-9])+-*$
  labels:
    app: postgres

spec:
  releaseName: default-postgres
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: postgresql
    version: 9.1.1
  valuesFrom:
    - secretKeyRef:
        name: postgres-release
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.9.0-debian-10-r48
    fullnameOverride: postgres

    persistence:
      size: 6Gi

    master:
      labels:
        app: postgres

    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 325Mi


---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: postgres-release
  namespace: default

spec:
  template:
    metadata:
      name: postgres-release
      namespace: default
  encryptedData:
    values.yaml: AgAqa9ZGI0BgcwSUmsJl+ubw4P4gBx1kVPxr8L2AOrQ27ug9oKCpaUhM/fIbsWHJfgNyPlSc63Bmo3i4LWbNDIUhMwFBi3G6fwc6MtP97xJnaXcRmWHIq7FEi0cdw5mb3cF1DhDA6COo9WeKBW/+923ap2q7Wpdn3MtCA8PkSMYLEyFCxyc4aDhLKo+J93mAgyOz8a4U8kOSUncSov0Z2e23ax6lLNtNd+jqH3VyitM7b+M+CUSkn1xz2erK4roUJnUZ4wkdgoiYqOKjyj3wEhRVyX358o5OjcmL1Bngnpyk72Uaw3jEuVWJPQYiXYN6VXsU2EahQOsPPXVWNaQlLiAayxZH4VMPj6aJLUvCtp+u37QsgCxWIzlsJUIRhTYTryapQjAJ63ZQdPmPF4srX1hkCr2pX5zq33MXIfcrnlaEotkeY7jKUMljlQt+AxDDsHpBnur/kpUZ7+pSJOcsMCerCYflqNlB1P3olH6YQwSiV1eBIHm5u8YOjAbSNFGvLbIG5E66c0Di8yr5QlCX7izG5hV46ysyNiyDs3XsEy0hPjaCSjEyqHIg4qHP9E0pX8ovqfX/YHz8OZWs9RJEvPhO4NhnIZMfGgp/+JTlkJEcbTgJohc6LDgCpCtmNtvEchJGp2JsY4nURc6YaOIIHqcU2/7GsJeU+CUGgsr7RYIqorM/nopRA1W0YtGcPi4cdQUUx7fPbmKI1yoKgxl8bMbg9uJ1+BYfrOzIEA3iQtQy0QJorB9CMnQwmplCH3A=
