---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: resume
  namespace: default
  labels:
    app: resume

spec:
  gateways: ["secondary.istio-system"]
  hosts: ["resume.stevenxie.com"]
  http:
    - redirect:
        authority: resume.stevenxie.me
