---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: rgv
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
  labels:
    app.kubernetes.io/name: rgv

spec:
  releaseName: rgv
  chart:
    repository: https://charts.stevenxie.me
    name: rgv
    version: 0.2.0

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: rgv
  namespace: default

spec:
  gateways: ["primary.istio-system"]
  hosts: ["rgv.stevenxie.me"]
  http:
    - match:
        - uri:
            prefix: /api
      rewrite:
        uri: /
      route:
        - destination:
            host: rgv-api
          headers:
            response:
              set:
                X-Service: rgv-api
    - route:
        - destination:
            host: rgv-frontend
          headers:
            response:
              set:
                X-Service: rgv-frontend
