---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: rgv
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
  labels:
    app.kubernetes.io/name: rgv

spec:
  releaseName: rgv
  chart:
    repository: https://charts.stevenxie.me
    name: rgv
    version: 0.2.0
