---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: rgv
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
  labels:
    app.kubernetes.io/name: rgv

spec:
  releaseName: rgv
  chart:
    repository: https://charts.stevenxie.me
    name: rgv
    version: 0.2.0
  values:
    frontend:
      service:
        annotations:
          getambassador.io/config: |
            apiVersion: ambassador/v1
            kind: Mapping
            name: rgv-frontend
            service: rgv-frontend.default
            host: rgv.stevenxie.me
            prefix: /
            add_response_headers:
              X-Service: rgv-frontend
            ---
            ## Redirect from rgv.stevenxie.com.
            apiVersion: ambassador/v1
            kind: Mapping
            name: rgv-frontend-redirect
            service: rgv.stevenxie.me
            host: rgv.stevenxie.com
            prefix: /
            host_redirect: true
    api:
      service:
        annotations:
          getambassador.io/config: |
            apiVersion: ambassador/v1
            kind: Mapping
            name: rgv-api
            service: rgv-api.default:3000
            host: rgv.stevenxie.me
            prefix: /api
            rewrite: /
            use_websocket: true
            add_response_headers:
              X-Service: rgv-api
