---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: traefik
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.hack: glob:2.*.*-alpine

spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: traefik
    version: 1.65.0
  valueFileSecrets:
    - name: traefik-release
  values:
    hack:
      image:
        repository: &repository traefik
        tag: &tag 2.0.0-alpine

    image: *repository
    imageTag: *tag
    cpuLimit: 250m
    memoryLimit: 100Mi
    nodeSelector:
      node-role.kubernetes.io/entrypoint: entrypoint

    kubernetes:
      namespaces:
      - default
      - wanderfall
    rbac:
      enabled: true

    deployment:
      hostPort:
        httpEnabled: true
        httpsEnabled: true

    serviceType: ClusterIP
    externalTrafficPolicy: ""
    service:
      nodePorts:
        http: []
        https: []

    ssl:
      enabled: true
      enforced: true  # redirect HTTP to HTTPS
    acme:
      enabled: true
      staging: false
      onHostRule: false
      challengeType: dns-01
      email: steven.xie@outlook.com
      dnsProvider:
        name: cloudflare
      domains:
        enabled: true
        domainsList:
        - main: "stevenxie.me"
        - main: "*.stevenxie.me"
        - main: "stevenxie.com"
        - main: "*.stevenxie.com"
        - main: "wanderfallgames.com"
        - sans:
          - "www.wanderfallgames.com"
          - "api.wanderfallgames.com"
      persistence:
        enabled: true
        size: 1Gi

    gzip:
      enabled: true

    metrics:
      prometheus:
        enabled: true
        restrictAccess: true

    dashboard:
      enabled: true
      statistics:
        recentErrors: 5
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: traefik-release
  namespace: default
  annotations:
    app.kubernetes.io/name: traefik

spec:
  encryptedData:
    values.yaml: AgDofgpv7lzQMefvEM8iGaSaTYh15uIXHChdO1z7cIGMfG1zctJb4FjA75x4VL7WCoAXIKzA9MpwGyzzx4hUBU6wuUi2OjhAdI8y4NWSMwlz4y4pkFAV9ik3PgnO+NBIfg+Vl2NnHbg/ObrO9WeCC1jb7MID44muUBW7aN/kw4I5CBz/6nS7jkXGRwTY0dBBwZhtBIfu7n5UGyZmbcPncdhURyFgRumK7tBNxemkVftdoN4W1gGbCijWUtAaMXSbvMy2mTezqOCpOikwP4pEP47zxjWTFa1kvmJlekLdiU7ehh/r+roSgbbT9ppLgEcAWj3owUvEn4knzRFtXctCnufmCwwCmYc8wHGwj56w8iiSnYqLbaREUKoYsCeKjTgnO+znRSa9mRsN79/nOUjvAaC7+IlMuq/H68lWCNkR4prTB2f8iIp00zCAPzsID2chdTAVPhFSJx4zYzyVKiggPfHz7LwhFjKS9lCjw/G8FANr64xy1/heGQ6K1FGXTYrxl0AtHSzv5cnSNqYmtU+aI5UZhBBgz2tOUG2ob2k3r/EDooextfVTG63VDpBBWzDarDmke5BCb4/loQksZE6pufZuNwdc2uPEv/v5vtaZrCD7inMGrklw7siEWIAccu2jBmC6PkOaADRRbIGZ8N1W4mUcPiq90UionjYl+6NkXSc5vKJnOLDYhLvyzzNixNxJeX3z+z3XgNrZ5lipLQ3lDDZruo0SjcnKZbEEz5/wkis+OPHhjcoR1xVBBkE1cYCikReeWov3IeAfWrSlOAfHlp7Msxe69rWLBsCPFEuh2alxCHGJzYD3ogbPLhrHu1tRsptNKOuYRnjLGMgovHjLeYbv1Of/mKJr4cUs2B2bU4/ak8CY+gZxJMHXWRqN8c8+D5kQhmdT
