---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: travelwise-site
  namespace: default
  labels:
    app: travelwise
    component: site

spec:
  gateways: ["stevenxie-me.istio-system"]
  hosts: ["travelwise.stevenxie.me"]
  http:
    - route:
        - destination:
            host: travelwise.netlify.com
          headers:
            response:
              set:
                X-Service: travelwise-site
