---

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry

metadata:
  name: travelwise-hasura
  namespace: default
  labels:
    app: travelwise
    component: hasura

spec:
  hosts:
    - systematic-lemongrass-d54k2ujifslyiuf5zz21vva5.herokudns.com
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
