---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: travelwise-api
  namespace: default
  labels:
    app: travelwise
    component: api

spec:
  template:
    metadata:
      name: travelwise-api
      namespace: default
      labels:
        app: travelwise
        component: api

  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgB5ab01ezfDmhhWmOSLefRLj+l1e+cFpnqcfFJLHTADCYWqJo2nxaScb6m9M/eBihKc03Xv75KjAtzgwmrE3Dp4QAPrxSXmJPslDkBItPC7Y1nSfe+DPTNV1W5wcRIh31iRwmk1tIVOqJLsn8DGeNFVG6eavIXPfO05gmSCVv+D6wI4MIj+naaVLHSa/ANNaEsDPaiWmFUKb1WOa9WOCsvbpEq4ALJmwxDzfwo86TybN3kKifPztlV+enbSrWVVwFk0duaB07wTkBk4pS+owsx3C1eFmzVp8Cvz052sX1Z2q6sukY0nOHfuBW9dNR9mhx+TsWHSJQ7FNPnZqy6SigCBDYSK8IqoGIKjccYgBzPbu6Ggr0fpCl2xlhXljVtoZoS+CA3xdVEFOW50Cw0MEBEtx0TbPQvmcgdAgK8zLz0tjvOn7PTA/GzUOQlCmsYphusTUBOKPFkAIRjgMih8K8JQNgZa/PO6qdfWf4Dqs2/bhi1UPbScEr46keCrJbNosZ3K8PMcHe5+agzgIGebvKPnbsXTlj3P2DRqO8Pz/Q1hxIgkbzZErD4cRamstu1LNnjSaxb09HKj3hc3/JAJU9SF+NMmIhCgVUWCPNeBNhVt33aXUBTDhtZ0HbPHvNrOxd2SLOEmyVY0vxbZ8gM6LX81Dl8EloiWfD40HifOmV8YgngOpKTpYja1wLS3KsFSfM5yPHBzH94URy3p7MQ=
    SESSION_SECRET: AgA/E/OP0dokh+YDevji/t6uTFohfh16z5GZzuE5QHD5vR0q2sozXeISVMfm19lzPgULH/CY+FPgvCsHo9lxJQsRo2Fp4GsCangp5wkoEaHb8RhJwjg/AB3IgIrLur5oDkMQ7mTNtIdNBbVv/fTZ7yC/TPUWEr4TYs/w5BMBUge1XtYAFFYvI8dcJdcssSPxGyR44G0sUWrU0KWnQYDWhdlWCLZsQIKAyuLukYaF0exKkixz3y03suvnF8YeYLXY7H5zu17ho2pNzISSxkvLGLP6+9KYcj6n+KOYQH3GxkGfduBuI2984uWCso92omqI4yCQJ/+wy2caRPsPxLP4mLkjRd8GRL4fKZqsYCjf2CYnAcEq663jSJOInfCWf52fyuyy82uBilH5VY+KQ3JA/IGFqtpyWcuqwBBpr+5S7etsNnLa7Jr0obehFeG/tyLE7xnXGXlppU1zDvxy+1F/y1zI+5Pn7kg5s3GrzhvFjDA6oa8xMrSo3guoy6GvtJEYxW66DUpWNzqH6qfmYkSzw9g16Q5FjsaHEAcl7oBA6n+Fhs6GF30zIEPw+VMNqIwplBFUEsP61Ni4kW3BvGgL3j4NkIeufiCr4TspWex0qsxtsRcVSxfbM91o2PvkU1oi+WlChjJi1iQ9fQDJiCITgf/RxcW1nE6NlqQg5r3U87pzJGsHpKX2j22FJf/AhnPJCb36AkGlNJkIdJmTX8F2SYwvamw5XjsvaAE=
