---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: varnish
  namespace: default
  labels:
    app: varnish

spec:
  gateways:
    - primary.istio-system
    - secondary.istio-system
  hosts:
    - api.stevenxie.me
    - api.stevenxie.com
  http:
    - match:
        - authority:
            exact: api.stevenxie.com
      redirect:
        authority: api.stevenxie.me
    - match:
        - authority:
            exact: api.stevenxie.me
      route: &route
        - destination:
            host: varnish
      corsPolicy:
        allowOrigin: ["*"]
        allowMethods: ["GET"]
    - route: *route
