---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: varnish
  namespace: default

spec:
  gateways:
    - primary.istio-system
    - secondary.istio-system
  hosts:
    - stevenxie.me
    - stevenxie.com
    - www.stevenxie.me
    - www.stevenxie.com
    - api.stevenxie.me
    - api.stevenxie.com
  http:
    - match:
        - authority:
            prefix: www
      redirect:
        authority: stevenxie.me
    - match:
        - authority:
            exact: stevenxie.com
      redirect:
        authority: stevenxie.me
    - match:
        - authority:
            exact: api.stevenxie.com
      redirect:
        authority: api.stevenxie.me
    - match:
        - authority:
            exact: api.stevenxie.me
      route: &route
        - destination:
            host: varnish
      corsPolicy:
        allowOrigin: ["*"]
        allowMethods: ["GET"]
    - route: *route
