---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: varnish
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: "semver:~6"
  labels:
    app.kubernetes.io/name: varnish

spec:
  releaseName: varnish
  chart:
    repository: https://charts.stevenxie.me
    name: varnish
    version: 0.1.1
  values:
    config:
      data: |-
        vcl 4.0;

        ## Backends:
        backend web {
          .host = "web";
          .port = "80";
        }
        backend api {
          .host = "api";
          .port = "3000";
        }

        sub vcl_backend_response {
          set beresp.ttl = 120s;
          set beresp.http.X-Service = beresp.backend.name;
        }

        sub vcl_recv {
          unset req.http.X-Body-Len;

          ## Determine backend.
          if (req.http.X-Forwarded-Host == "api.stevenxie.me") {
            set req.backend_hint = api;
          }

          ## Remove has_js and Cloudflare/Google Analytics __* cookies, and
          ## normalize cookies.
          set req.http.Cookie = regsuball(req.http.Cookie,
            "(^|;\s*)(_[_a-z]+|has_js)=[^;]*", "");
          set req.http.Cookie = regsub(req.http.Cookie, "^;\s*", "");
          if (req.http.Cookie ~ "^ *$") {
            unset req.http.Cookie;
          }

          if (req.method != "GET" && req.method != "HEAD") {
            return (pass);
          }
          if (req.http.Authorization) {
            return (pass);
          }
          if (req.http.X-Force-Backend) {
            return (pass);
          }
        }

        sub vcl_deliver {
          unset resp.http.Via;
          return (deliver);
        }

    storage:
      backend: file

    image:
      repository: cooptilleuls/varnish
      tag: 6.2.0-alpine

    deployment:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

    ingress:
      enabled: true
      hosts:
        - host: stevenxie.me
          paths: ['/']
        - host: api.stevenxie.me
          paths: ['/']
