---

apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: veritaserum
  namespace: default
  labels:
    app: veritaserum
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.app: regexp:^0(\.[0-9]+){2} # 0.x.x...

spec:
  selector:
    matchLabels:
      app: veritaserum
  template:
    metadata:
      labels:
        app: veritaserum
    spec:
      containers:
      - name: app
        image: stevenxie/veritaserum:0.2.1
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        envFrom:
        - secretRef:
            name: veritaserum
        env:
        - name: VERITASERUM_DEBUG
          value: "false"
        resources:
          requests:
            cpu: 5m
            memory: 25Mi
          limits:
            cpu: 50m
            memory: 75Mi
