---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: veritaserum
  namespace: default

spec:
  template:
    metadata:
      name: veritaserum
      namespace: default

  encryptedData:
    MESSENGER_SESSION: AgBaIe1ZPleh2peopalIRbNPJNtGsfQ1CJpMB/p8ls8atn+Q64lG+WjE5iA8jiT+SHafzGr/mtz3rgJKbeQ0OeJ1vUvNTt5IiP7VUBrl7yktJ2vDvtKn9qtDOKXmKlutsK/xDqQdW1pvnWLtbjrj0j1yg1TWBIDCARlkdDqJ86/rBvpcgZCaKXIafvDGG+TQ1Zeech2VWSK28ltdusuSO3GlVozA4NjzISKo32yPDOpPZNIeq/FJ1T2ssBj+aMlhFmgzirALBFnlHD2NNLEAg65Qd0spYpmk5dplVGuYdPMzgI59iTPY8On0IfHio2waheatnSB3uIaFXkz0fDl5b9PYt/ryIhVfa/fIzpYtIbr+8DSh/GEkeW9FvosUnHYymQuB3zrg8TVPYizTaLTwWWLT5a6TwI+YIXIE5DUhq2qQ/UxV3uDpcITF9yo6bmrCU1w9rnxQ7/KjC1ZYwuFQ3nTpG4VPWCd5Cfy0POuvrLHhjBEh9Uwnl7C5CgRG/Ka1QuuDYCPRuDaVTSHzjTNEoKsdckBlSOH0k+0AKIsr1od1QcOGUl0/Kb1JQrTiR8n6c6TH06HhRJAOj1uQgY2RiGb3uAxrpab77pwQbY0omQTkNRp0V8GR51d+hVo8OKAFuqKpg+k9ODE3GJMBL4NfwyXbwcCuh8hSW1yUCFbb0kD2Lc+yQUHuEKfTGCgtn+qcrajmE4QhZrUSeqWqCupk8+5oOTdSpy1fOWKvmL7ZvkgXw2FmXnWvp2onDK2Yaw93QU5IkcQhYrUSr49vMVYTnwzvzNEkkCpsHNIJjb8BjNrpEjQTLZmlT3D7cGwo31k0mZuJ9TO1fn63of+KRN1KkyWaUijunf+BmRaRPFT+B94yrarB4XXW/RqRGQdYkn3SqfNaEe+Ri7Q/nKs0txq85TNV62UTsGybV4RZ25xe3SD8KeyFMBzIIBeedC3xxy+D7TqUtyIxgexBjesLaYiVKrAQFxITzo7HYb+6R/n2Z7pVz00SelpBCqDC9bL4QD4hp5M+wSy3+0ftOFL7pU9QPeM5M4apxh00jFhInXz0DP7JirPNhEv20L13l4Se8iJTNYNtSQvu5fRuidGyZOYAVswpVb+5fQs38otRZa89M5N9FDhUwoEhJPoCxmzQ76udDO/T2e1sRmbFYCTcKffIz979MacjjZETUDW7d2TswMRkTXhxyCADaiWUQLJXr3wiltz0nyql2v29IZ1oQypnM/FcKZw+qiNeDFuGIQqrO4QyNfB7Hytu16E9jTWDutVqvs/2dcyPOwq61Is/xyJY8h9nfU2m+5qwwpo=
