---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: veritaserum
  namespace: default

spec:
  template:
    metadata:
      name: veritaserum
      namespace: default

  encryptedData:
    MESSENGER_SESSION: AgAmPdMJ5EdNGTPp3wkOn2I/cixutDheCFAHzhOS/J1ATVCjVQ5u6ry0vOXQpBB6mSV1eAp92mKMYmOJknLY0pxswEJIAtFNCRZVeMC8jU7787a3gK8xegOfbbq/0k7T5CmLHBlhgoJzeOiL397w4CJyBqgamCzpTj3q/xbkM7IefCA02CZ+WWKxCF20voDgjLjmJ3IE2feyui/caPB7WxMEgUh+XwRqK0xf/q7bA8fOzeXtJwx2cxTFtRywgwdNQryep9jyXmuUspJ33v/W45e6et6gYe2MHIz9fWbbPx8csBroTTuTphDFGx6YCX6x+BKXH56mpVvOK4jemCnGaEpQR61KymvPtiTFvm8EfirrbbJCjsYjwUZCp+1CskaP0YoFsWV/A2kIINMYX5TWjz8aQxfTPnpNRA9DORVJ1ggNi43BAE0YwPTJSIssLnooGsHuGWqDezLlwdAVnBhOMNvQV0KHGspKr6AOzCNWiqq/maD+V4/AkYR6sqET1/yQNYJ6jaldXS8QCol/TAi/WJy2YIpoqRVrhsMp8Kgl4Bw+YG0VXPKnQEdSMp6Jj5gu7wGvfWDEh1ft/aFnSr94OhNYQDsGWXgrY6Mi51FjnoQO3auvRbO27b6E7rcdzduLpjF1fo/pr9tSLmDivf/VZnBVCAyNiSl8DACq5HhMyBjTtTLQk6E9FaUx7r3HuFuivkdicAaxP/dEZ8qG/1my1wvu7caXTjOULX40q0RAGcjuwYO+EW14BWJGJx1KyAYFk3AuPvHRYUKL6Ku49aP0xS/ny+5dJWnK4zWRArn+YZRnMbVbrBZtO1pYBcHBUW2KAfVWOsS2A66jneXhefkxjpU6Xtx6dYFgV9B+nDWmqorTwLZXiYhDLluJMLjLSmpueEbKig4IsKhcDfcwxdZRPdB2ZhvjKGaZ/fpbcMpYWlF/5DtVgV7Kiz+vduwoITFFairOwR/5o6otzkxFi2HXgJDHv8G9CRAW42WrqTa8My9ai+SYEhHpJJ8sC/fNH9Py0fhJf/W+PUlANPxFlUt19Me+azKcB87/S99QTldsKE3TrXIAtd0s6W+xdnmKf0WTzFtD3hPHXNsN/4qzzfWOqzVE2veQ9cSIDQoyc0Ya6XDBeSJ/MOv5qUXbgMDa81GH3Mn0gAkpE8QHFoYqrKcVcuvgUruqbonuYiFfoaljoPVisR6bz/kIiGF6149PHFDP2x0p2ktuRybJyOxno+CifYXr4b67I0ml843L23gRdE7dr1lZDDaftvEex3bjhQTQSw4yRE1asEOcWy3hawceAlK92y9PIuX/Bag=
