---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: web
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: regexp:^0(\.[0-9]+){2} # 0.x.x...
  labels:
    app.kubernetes.io/name: web

spec:
  releaseName: web
  chart:
    repository: https://charts.stevenxie.me
    name: web
    version: 0.1.1
  values:
    image:
      repository: stevenxie/stevenxie.me
      tag: 0.1.0-14-g5aedcb9

    deployment:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

    resources:
      limits:
        memory: 200Mi

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService

metadata:
  name: web
  namespace: default

spec:
  gateways: ["primary.istio-system"]
  hosts: ["web-direct.stevenxie.me"]
  http:
    - route:
        - destination:
            host: web
          headers:
            response:
              set:
                X-Service: web-direct
