---

apiVersion: flux.weave.works/v1beta1
kind: HelmRelease

metadata:
  name: web
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: regexp:^0(\.[0-9]+){2} # 0.x.x...
  labels:
    app.kubernetes.io/name: web

spec:
  releaseName: web
  chart:
    repository: https://charts.stevenxie.me
    name: web
    version: 0.1.1
  values:
    image:
      repository: stevenxie/stevenxie.me
      tag: 0.1.0-14-g5aedcb9

    deployment:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

    resources:
      limits:
        memory: 200Mi

    service:
      annotations:
        getambassador.io/config: |
          ## Direct access.
          apiVersion: ambassador/v1
          kind: Mapping
          name: web
          service: web.default
          host: web-direct.stevenxie.me
          prefix: /
          add_response_headers:
            X-Service: web-direct
          ---
          ## Redirect from www.stevenxie.me.
          apiVersion: ambassador/v1
          kind: Mapping
          name: web-redirect-www
          service: stevenxie.me
          host: www.stevenxie.me
          prefix: /
          host_redirect: true
          ---
          ## Redirect from stevenxie.com.
          apiVersion: ambassador/v1
          kind: Mapping
          name: web-redirect-com
          service: stevenxie.me
          host: stevenxie.com
          prefix: /
          host_redirect: true
          ---
          ## Redirect from www.stevenxie.com.
          apiVersion: ambassador/v1
          kind: Mapping
          name: web-redirect-com-www
          service: stevenxie.me
          host: www.stevenxie.com
          prefix: /
          host_redirect: true
