---

apiVersion: v1
kind: ConfigMap

metadata:
  name: barista
  namespace: uwcnc

data:
  BARISTA_DEBUG: "false"
  BARISTA_HOSTS: localhost,.uwcoffeencode.com
  BARISTA_SLACK_CHANNEL: system
  BARISTA_USE_FORWARDED_HOST: "true"
  BARISTA_DB_NAME: uwcnc_barista
  BARISTA_DB_USER: uwcnc
  BARISTA_DB_HOST: frost-do-user-2931318-0.b.db.ondigitalocean.com
  BARISTA_DB_PORT: "25061"
  BARISTA_DB_SSLMODE: require

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: barista
  namespace: uwcnc

spec:
  template:
    metadata:
      name: barista
      namespace: uwcnc
  encryptedData:
    BARISTA_SLACK_TOKEN: AgCNzlkuElkS3iH16JspH1fa7SlSk2GiZnfvTKph46QFc7unHSFtTZ/vIRizsLE3/kTayIW0LD+gAq/UEet4fMjSeTdy1UEyEqqMWMsHFP3ewOmoLvJpGXh+5RfyQkW/Jn2s2+massWvDD45FvLmQ+AF80XBo9Aj2b3M1+OXjhf35BaisWbhkMUYbwvjAuKYC1zU5PgxB4UQmyMw6s15p2nnwNe6jARff9R1vF6D8gQQm70E1VuhwlYX+WP3r1vXv+sar8F89wWpD2J6cdnJxNE+OZnHNxorhT//9ppRUdgta6kdWjIhwLwItLnJ8wvFTyAveiZYFfeE8M/yTUWzdfU0OJKfWGN3qRyznDDLgh5O1bWXLV+Zo2nst7rp4DZ1ntIwiKIaDPkirxaeokCloB9tDCDJmiPscJNJAaA7Dov56wV8LdHBmrxJCZus6oUND6s7adTsHbGRNJCMsxzCmYkRuggeQX8AuMBbUYNCHTW/lBivg9g2JXIrufzfdcLK8fUGQDt2WRNCS9WmBCAixRaP4M7SU0bKpDrlcBONRGfcnsfYC7L1cI43Uri55ri3EbZJqaupE9+YNXiIO4DnmEim2IniiNyPKCrKnSMZJrFqYYn11Nz4tmjzBdwMnfbH0jwZSTqqZ67ZD480vjD0U77DWZKH0+O3khVIjmP/d00m0GsdwqFwNo1s0/ZXnIuX1RGJADb/dLaySu34yap0p9Nsr4iJObCJ3xtX0uUAg9c+oRSulWv26+LlsFsWPTSUEinia3pi2Mkjvg==
    BARISTA_SLACK_SECRET: AgC1SChflBb0H4UUOL0L2f4q4W6Iwwr3xYuE2q9ef6EvWzAKVYFg91+0yxKPyQ66Cow1zOtNBJpcrbw2bd7MYXsmU4KYvDBgAGvcZGXUbHaU7AqdB2oUN7jPX0u+s9BGO6q12wy3hJwey8lGAEkJlEHaXlaJmSKOUCn2lNMYYkqVuo7x+oaIwXPkBSjPFjXE+aV5U8vCeJIAajpTxzDqCQKSxUnmetf+kEGx/SZzoNBd/x9bDQp4kvP5n55vRTQiY2cneaUPkHTucy08q4Pk6HpBmw8+mFPCtTHGQf+qjEmg+ttGYeWdEaNwslhxjBqUMDwYlFNIPOHka2ND+7Q628r7SwT4HPGeKkl/N2f8k+VzQkTiapiZWdVogoRu8Cb6+EEkqhD1eg8/ybu7jyCjlhrveco+tt7/0L4BvkdyEIT7qsQAfENEIBKgo+wJQMTvyowH322QqeiiG1z2vATX5Mbwk9zsNGN9dPA86TUlyjhE7i6WCLFZWcj6P1GR+Z82GZTASsr7hdVNVYWbX6JWZRjNcejxMQDVxdfjE+slt1eJbr91pv8S6J1FVt9YHYUd7uh+8s/baoqzIwixIJ3JEmVMMlBrF1Ek8Bf6T1IRRRFopSFPtEStkB5qbvob1lF0vGzielFygLiBD00uCSuNhCe8qkEgPeMwYdeNT/6cgFsL8wbE1uhmPmVUJEOvP10q4bSQN0rlil6CnXJ5u+37kpj+2xZnoeeQGsAF6Y6YRqLObw==
    BARISTA_SECRET: AgA3rt/jehie+0Uz9C/71YOS7iW9SBtnAaDkGPMf0t0aUyF1lCH+NJ4Yyp+R+U5aXYMiCwKuyy53ZjJQz2qqFzcuNKqAWvwWIfYU/WHPetQscosQWWqKiX31B8rKX+7WLEsT5kXJ773e3ck1FLIPFfEvA1zfZpV+EGTGKLvGHIjO8+g7G6oBGTahLuW0t6DZpueYKt1noAQxSy+FVO+h1G71sfLnpdd3u5WdeYgRt7RrOTU5UqCfyiRn1ECqozcL0rVYcpz0ZJ8WTZQQ2hSdg8oYVB6Q4uy2TyftmCWEnbJmLV0HdVvAJ6HdxiSxsA/XCmF1PRFTED5YT7TjMKVMSdhVnIkgqL/+lPLFI2Uz2rP417dWBlzfJwFMnBDS1L6K+CqTQRF6bFJoISf9dfIzo54j9bIp/A2BmzrPKnviwbug1/BUX1x8v95dN/6NYxvlQainUx6r+yAHpK5ZhxAOQA0COD1vHscA7QzEYd2Tg9SqEBC9kK7Q2Pi6EFdKn8r2ydmT4VXrfEswho62E10cBTHlh80iF2uIKMgVu926vkD63Tr3w3RLVbW58J0gA3U+B1PMWUNs5r5SH4MQqGastkfhPBLhp0FxmobUOR6Stejw8UqepmA2AVty70QS+1uydfYhUwJW3xUnEECXZ3WOZ2/R6XkO0Hw3zbvS+sUmbZRrSsnybhcriY/9OY3Pa7W3S7LQnqoe/TDq1lyoTbFRZc795w/Fm7+1Y5eU1LNpuO6Un8NE/J0I8hwiuh/PQ3wWAoJ2+Q==
    BARISTA_DB_PASSWORD: AgBb7ABIiaU0ypziMdO3Irzbd2wNAugOSshSnJA6kMEBWjrGmZa8RrhTrl1Ne55wTaRRVwVI6N6omuForqutK0xXmbXOKsxdwqzgr06k63lrcEHR+I/R8EV8Bo5MWOuo4UjauYB8zFlh6Y4NuGajQ5wa+JMdY56i3MJ4OI/SYBLTCOWy6YWClNrfKPFogaRJ81cFY41ZgG6HlTYcppQuy4FWzTYM1RlFlX4JnnUS4y2Md02od4NfW5gHm4C074XnD7xpqqwCJp/gPqJZSL1UQNI19IgQu/WEFxgVXcO+9zWVE2AYra/w8Tsak/RWihQnCDPkv571xONleTaMaKVrC+Gw9TwX9D6AoxuV7Q6Lkg28x3OHVYQc7vaN7oamJHzvIfxk1Xe5waZ2xdCvg1P4++K6f0OAbhQr1/k81LB59xMysUiHHiDceD9zGe3svrOLqLBBXSKjlqh6TeaVlailD72lsC2iRpNzDTULC7gD3Z8HAthzQgV9rv9VQo/ndM4fTMZxQ+ehQSwEt3l3+lKcEbKg1ZMtjz8X2D49y4mf8EYfn0N7oK1V1TOl7fnSinvmDKhJFnwNIpyvx63X1W9YF7N7Nucj/+8GH0lYMqmJ5v78/VD8/EJp4f/8D/YTH8g+BVKJo2LUZLy2JBW6UgWmPo3tadTd+TEOsOk0k+kaucJMTA9DHkbrEXxuPIsEEdf8fCvyljA2FHZKJ8+j/hizVTcm
    BARISTA_RECAPTCHA_SECRET: AgCtSCVKkRGj8jtZOro4Y3OELEP5OdwAgqb7/4kxqIDJ13e+X6EOH1zFXzbVo5IeqXNnnZntrcTkwgBTpkz8RyQ/qnK4qy2KZWTXr/aW/8vKTjo5C2wN9JwT3r+UcAJM+/usPfsJsRLM9M4P59GQNDyyFWnV6clOOJkbJVxXxWUDkK+ePOrRms8kZ+K6FjCKzd7TcHkx0Do7ftHqsQdqu9Gx0WZQf7cJziAFyVnCvVVu5HlocV8Z5DWNui/e5wa16KRgb2tZ7cYCw/bPbKAHVE7iuIrx86cmUsG5V8x1Az+oUlU8zd/e9uzxO7satAd+cqOhoHLY0K8Ijbto/Ae8AmVFKIOaX28LZiDhYnVisces7oVrKrC/rEaXjNmuJePlhbjTeluid7iseORKu9YGHtALE/gqX6+fXrg60FU53hn8tLflfiAjjIb5bD0V9Ah7ldjFKrrVXB1pWbNK0zD5ULLr1zDm1qmkGDETqmjt9uC+2s1ybWI90RZ1PJM9ZNkl1/tVV0nFB2PFs1L5bS4OAYRH2dJR4NLNaUzczA5afoJD98hULQAiYVPbxya/g9oFIiQdOQVTL86yreaHGiQFfrKA3e98eKPDKcrDDp/j9AEIstPrX+e84CYrqT+wjwp6ki/yGDJ/booE7U4Cr+1M9n4BGQAHJMc9CiVds21N4qUkq08LkN/Cm87LZuC6EXNyLarKuNfsTG69PIXLupl+QBTr5rRwt2yKftADgXvwcoh0liQzq7MxKqsr
