---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: build-controller
  namespace: knative-build

spec:
  selector:
    matchLabels:
      app: build-controller
  template:
    metadata:
      labels:
        app: build-controller
    spec:
      serviceAccountName: build-controller
      containers:
        - name: build-controller
          image: gcr.io/knative-releases/github.com/knative/build/cmd/controller:v0.5.0
          args:
            - -logtostderr
            - -stderrthreshold
            - INFO
            - -creds-image
            - gcr.io/knative-releases/github.com/knative/build/cmd/creds-init@sha256:ebf58f848c65c50a7158a155db7e0384c3430221564c4bbaf83e8fbde8f756fe
            - -git-image
            - gcr.io/knative-releases/github.com/knative/build/cmd/git-init@sha256:09f22919256ba4f7451e4e595227fb852b0a55e5e1e4694cb7df5ba0ad742b23
            - -nop-image
            - gcr.io/knative-releases/github.com/knative/build/cmd/nop@sha256:a318ee728d516ff732e2861c02ddf86197e52c6288049695781acb7710c841d4
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 0
              memory: 0
            limits:
              cpu: 600m
              memory: 600Mi
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging

---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: build-controller
  namespace: knative-build

---

apiVersion: v1
kind: Service

metadata:
  name: build-controller
  namespace: knative-build
  labels:
    app: build-controller

spec:
  selector:
    app: build-controller
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
