---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

metadata:
  name: buildtemplates.build.knative.dev
  labels:
    knative.dev/crd-install: "true"

spec:
  group: build.knative.dev
  version: v1alpha1
  scope: Namespaced
  names:
    categories:
      - all
      - knative
    kind: BuildTemplate
    plural: buildtemplates
  additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  subresources:
    status: {}
