---

apiVersion: caching.internal.knative.dev/v1alpha1
kind: Image

metadata:
  name: git-init
  namespace: knative-build

spec:
  image: gcr.io/knative-releases/github.com/knative/build/cmd/git-init:v0.5.0
