varnish:
  image:
    tag: 6.2.0-alpine

  config:
    data: |-
      vcl 4.0;

      # Backends:
      backend web {
        .host = "web";
        .port = "80";
      }
      backend api {
        .host = "api";
        .port = "3000";
      }

      sub vcl_backend_response {
        set beresp.ttl = 120s;
        set beresp.http.X-Service = beresp.backend.name;
      }

      sub vcl_recv {
        unset req.http.X-Body-Len;

        # Determine backend.
        if (req.http.Host == "api.stevenxie.me") {
          set req.backend_hint = api;
        }

        # Remove has_js and Cloudflare/Google Analytics __* cookies, and
        # normalize cookies.
        set req.http.Cookie = regsuball(req.http.Cookie,
          "(^|;\s*)(_[_a-z]+|has_js)=[^;]*", "");
        set req.http.Cookie = regsub(req.http.Cookie, "^;\s*", "");
        if (req.http.Cookie ~ "^ *$") {
          unset req.http.Cookie;
        }

        if (req.method != "GET" && req.method != "HEAD") {
          return (pass);
        }
        if (req.http.Authorization) {
          return (pass);
        }
        if (req.http.X-Force-Backend) {
          return (pass);
        }
      }

      sub vcl_deliver {
        unset resp.http.Via;
        return (deliver);
      }

  resources:
    requests:
      cpu: 0
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

  deployment:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
