metrics-server:
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 100m
      memory: 100Mi
